// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)

// OutboxEvent is the predicate function for outboxevent builders.
type OutboxEvent func(*sql.Selector)

// PurchaseOrder is the predicate function for purchaseorder builders.
type PurchaseOrder func(*sql.Selector)
