apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eagle
resources:
  - namespace.yaml
  - configmap.yaml
  - deployments.yaml
  - services.yaml
  - migrations.yaml
  - gateway.yaml
  - pdb.yaml
  - hpa.yaml
  - networkpolicy.yaml
images:
  - name: registry.example.com/eagle/admin
    newTag: dev
  - name: registry.example.com/eagle/product
    newTag: dev
  - name: registry.example.com/eagle/order
    newTag: dev
