// Code generated by ent, DO NOT EDIT.

package accountroleaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountroleaudit type in the database.
	Label = "account_role_audit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAudience holds the string denoting the audience field in the database.
	FieldAudience = "audience"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldAccountSubject holds the string denoting the account_subject field in the database.
	FieldAccountSubject = "account_subject"
	// FieldActorSubject holds the string denoting the actor_subject field in the database.
	FieldActorSubject = "actor_subject"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldBefore holds the string denoting the before field in the database.
	FieldBefore = "before"
	// FieldAfter holds the string denoting the after field in the database.
	FieldAfter = "after"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the accountroleaudit in the database.
	Table = "account_role_audit"
)

// Columns holds all SQL columns for accountroleaudit fields.
var Columns = []string{
	FieldID,
	FieldAudience,
	FieldRevision,
	FieldAccountSubject,
	FieldActorSubject,
	FieldAction,
	FieldBefore,
	FieldAfter,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AudienceValidator is a validator for the "audience" field. It is called by the builders before save.
	AudienceValidator func(string) error
	// AccountSubjectValidator is a validator for the "account_subject" field. It is called by the builders before save.
	AccountSubjectValidator func(string) error
	// ActorSubjectValidator is a validator for the "actor_subject" field. It is called by the builders before save.
	ActorSubjectValidator func(string) error
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AccountRoleAudit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAudience orders the results by the audience field.
func ByAudience(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudience, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByAccountSubject orders the results by the account_subject field.
func ByAccountSubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountSubject, opts...).ToFunc()
}

// ByActorSubject orders the results by the actor_subject field.
func ByActorSubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorSubject, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
