// Code generated by ent, DO NOT EDIT.

package authsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/eagle-go/eagle/internal/platform/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldContainsFold(FieldID, id))
}

// IdentityID applies equality check predicate on the "identity_id" field. It's identical to IdentityIDEQ.
func IdentityID(v int64) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldIdentityID, v))
}

// RefreshTokenHash applies equality check predicate on the "refresh_token_hash" field. It's identical to RefreshTokenHashEQ.
func RefreshTokenHash(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldRefreshTokenHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// IdentityIDEQ applies the EQ predicate on the "identity_id" field.
func IdentityIDEQ(v int64) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldIdentityID, v))
}

// IdentityIDNEQ applies the NEQ predicate on the "identity_id" field.
func IdentityIDNEQ(v int64) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldIdentityID, v))
}

// IdentityIDIn applies the In predicate on the "identity_id" field.
func IdentityIDIn(vs ...int64) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldIdentityID, vs...))
}

// IdentityIDNotIn applies the NotIn predicate on the "identity_id" field.
func IdentityIDNotIn(vs ...int64) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldIdentityID, vs...))
}

// IdentityIDGT applies the GT predicate on the "identity_id" field.
func IdentityIDGT(v int64) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldIdentityID, v))
}

// IdentityIDGTE applies the GTE predicate on the "identity_id" field.
func IdentityIDGTE(v int64) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldIdentityID, v))
}

// IdentityIDLT applies the LT predicate on the "identity_id" field.
func IdentityIDLT(v int64) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldIdentityID, v))
}

// IdentityIDLTE applies the LTE predicate on the "identity_id" field.
func IdentityIDLTE(v int64) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldIdentityID, v))
}

// RefreshTokenHashEQ applies the EQ predicate on the "refresh_token_hash" field.
func RefreshTokenHashEQ(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldRefreshTokenHash, v))
}

// RefreshTokenHashNEQ applies the NEQ predicate on the "refresh_token_hash" field.
func RefreshTokenHashNEQ(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldRefreshTokenHash, v))
}

// RefreshTokenHashIn applies the In predicate on the "refresh_token_hash" field.
func RefreshTokenHashIn(vs ...string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldRefreshTokenHash, vs...))
}

// RefreshTokenHashNotIn applies the NotIn predicate on the "refresh_token_hash" field.
func RefreshTokenHashNotIn(vs ...string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldRefreshTokenHash, vs...))
}

// RefreshTokenHashGT applies the GT predicate on the "refresh_token_hash" field.
func RefreshTokenHashGT(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldRefreshTokenHash, v))
}

// RefreshTokenHashGTE applies the GTE predicate on the "refresh_token_hash" field.
func RefreshTokenHashGTE(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldRefreshTokenHash, v))
}

// RefreshTokenHashLT applies the LT predicate on the "refresh_token_hash" field.
func RefreshTokenHashLT(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldRefreshTokenHash, v))
}

// RefreshTokenHashLTE applies the LTE predicate on the "refresh_token_hash" field.
func RefreshTokenHashLTE(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldRefreshTokenHash, v))
}

// RefreshTokenHashContains applies the Contains predicate on the "refresh_token_hash" field.
func RefreshTokenHashContains(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldContains(FieldRefreshTokenHash, v))
}

// RefreshTokenHashHasPrefix applies the HasPrefix predicate on the "refresh_token_hash" field.
func RefreshTokenHashHasPrefix(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldHasPrefix(FieldRefreshTokenHash, v))
}

// RefreshTokenHashHasSuffix applies the HasSuffix predicate on the "refresh_token_hash" field.
func RefreshTokenHashHasSuffix(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldHasSuffix(FieldRefreshTokenHash, v))
}

// RefreshTokenHashEqualFold applies the EqualFold predicate on the "refresh_token_hash" field.
func RefreshTokenHashEqualFold(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEqualFold(FieldRefreshTokenHash, v))
}

// RefreshTokenHashContainsFold applies the ContainsFold predicate on the "refresh_token_hash" field.
func RefreshTokenHashContainsFold(v string) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldContainsFold(FieldRefreshTokenHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldExpiresAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotNull(FieldRevokedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AuthSession {
	return predicate.AuthSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthSession) predicate.AuthSession {
	return predicate.AuthSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthSession) predicate.AuthSession {
	return predicate.AuthSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthSession) predicate.AuthSession {
	return predicate.AuthSession(sql.NotPredicates(p))
}
