// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eagle-go/eagle/internal/platform/database/ent/accountrolestate"
)

// AccountRoleStateCreate is the builder for creating a AccountRoleState entity.
type AccountRoleStateCreate struct {
	config
	mutation *AccountRoleStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRevision sets the "revision" field.
func (_c *AccountRoleStateCreate) SetRevision(v int64) *AccountRoleStateCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *AccountRoleStateCreate) SetNillableRevision(v *int64) *AccountRoleStateCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetAdminInitialized sets the "admin_initialized" field.
func (_c *AccountRoleStateCreate) SetAdminInitialized(v bool) *AccountRoleStateCreate {
	_c.mutation.SetAdminInitialized(v)
	return _c
}

// SetNillableAdminInitialized sets the "admin_initialized" field if the given value is not nil.
func (_c *AccountRoleStateCreate) SetNillableAdminInitialized(v *bool) *AccountRoleStateCreate {
	if v != nil {
		_c.SetAdminInitialized(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountRoleStateCreate) SetUpdatedAt(v time.Time) *AccountRoleStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountRoleStateCreate) SetNillableUpdatedAt(v *time.Time) *AccountRoleStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountRoleStateCreate) SetID(v string) *AccountRoleStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AccountRoleStateMutation object of the builder.
func (_c *AccountRoleStateCreate) Mutation() *AccountRoleStateMutation {
	return _c.mutation
}

// Save creates the AccountRoleState in the database.
func (_c *AccountRoleStateCreate) Save(ctx context.Context) (*AccountRoleState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountRoleStateCreate) SaveX(ctx context.Context) *AccountRoleState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountRoleStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountRoleStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountRoleStateCreate) defaults() {
	if _, ok := _c.mutation.Revision(); !ok {
		v := accountrolestate.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	if _, ok := _c.mutation.AdminInitialized(); !ok {
		v := accountrolestate.DefaultAdminInitialized
		_c.mutation.SetAdminInitialized(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountrolestate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountRoleStateCreate) check() error {
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "AccountRoleState.revision"`)}
	}
	if _, ok := _c.mutation.AdminInitialized(); !ok {
		return &ValidationError{Name: "admin_initialized", err: errors.New(`ent: missing required field "AccountRoleState.admin_initialized"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountRoleState.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := accountrolestate.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AccountRoleState.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AccountRoleStateCreate) sqlSave(ctx context.Context) (*AccountRoleState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AccountRoleState.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountRoleStateCreate) createSpec() (*AccountRoleState, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountRoleState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountrolestate.Table, sqlgraph.NewFieldSpec(accountrolestate.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(accountrolestate.FieldRevision, field.TypeInt64, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.AdminInitialized(); ok {
		_spec.SetField(accountrolestate.FieldAdminInitialized, field.TypeBool, value)
		_node.AdminInitialized = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountrolestate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountRoleState.Create().
//		SetRevision(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountRoleStateUpsert) {
//			SetRevision(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountRoleStateCreate) OnConflict(opts ...sql.ConflictOption) *AccountRoleStateUpsertOne {
	_c.conflict = opts
	return &AccountRoleStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountRoleState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountRoleStateCreate) OnConflictColumns(columns ...string) *AccountRoleStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountRoleStateUpsertOne{
		create: _c,
	}
}

type (
	// AccountRoleStateUpsertOne is the builder for "upsert"-ing
	//  one AccountRoleState node.
	AccountRoleStateUpsertOne struct {
		create *AccountRoleStateCreate
	}

	// AccountRoleStateUpsert is the "OnConflict" setter.
	AccountRoleStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetRevision sets the "revision" field.
func (u *AccountRoleStateUpsert) SetRevision(v int64) *AccountRoleStateUpsert {
	u.Set(accountrolestate.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *AccountRoleStateUpsert) UpdateRevision() *AccountRoleStateUpsert {
	u.SetExcluded(accountrolestate.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *AccountRoleStateUpsert) AddRevision(v int64) *AccountRoleStateUpsert {
	u.Add(accountrolestate.FieldRevision, v)
	return u
}

// SetAdminInitialized sets the "admin_initialized" field.
func (u *AccountRoleStateUpsert) SetAdminInitialized(v bool) *AccountRoleStateUpsert {
	u.Set(accountrolestate.FieldAdminInitialized, v)
	return u
}

// UpdateAdminInitialized sets the "admin_initialized" field to the value that was provided on create.
func (u *AccountRoleStateUpsert) UpdateAdminInitialized() *AccountRoleStateUpsert {
	u.SetExcluded(accountrolestate.FieldAdminInitialized)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountRoleStateUpsert) SetUpdatedAt(v time.Time) *AccountRoleStateUpsert {
	u.Set(accountrolestate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountRoleStateUpsert) UpdateUpdatedAt() *AccountRoleStateUpsert {
	u.SetExcluded(accountrolestate.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AccountRoleState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accountrolestate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountRoleStateUpsertOne) UpdateNewValues() *AccountRoleStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(accountrolestate.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountRoleState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountRoleStateUpsertOne) Ignore() *AccountRoleStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountRoleStateUpsertOne) DoNothing() *AccountRoleStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountRoleStateCreate.OnConflict
// documentation for more info.
func (u *AccountRoleStateUpsertOne) Update(set func(*AccountRoleStateUpsert)) *AccountRoleStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountRoleStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetRevision sets the "revision" field.
func (u *AccountRoleStateUpsertOne) SetRevision(v int64) *AccountRoleStateUpsertOne {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *AccountRoleStateUpsertOne) AddRevision(v int64) *AccountRoleStateUpsertOne {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *AccountRoleStateUpsertOne) UpdateRevision() *AccountRoleStateUpsertOne {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.UpdateRevision()
	})
}

// SetAdminInitialized sets the "admin_initialized" field.
func (u *AccountRoleStateUpsertOne) SetAdminInitialized(v bool) *AccountRoleStateUpsertOne {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.SetAdminInitialized(v)
	})
}

// UpdateAdminInitialized sets the "admin_initialized" field to the value that was provided on create.
func (u *AccountRoleStateUpsertOne) UpdateAdminInitialized() *AccountRoleStateUpsertOne {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.UpdateAdminInitialized()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountRoleStateUpsertOne) SetUpdatedAt(v time.Time) *AccountRoleStateUpsertOne {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountRoleStateUpsertOne) UpdateUpdatedAt() *AccountRoleStateUpsertOne {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountRoleStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountRoleStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountRoleStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountRoleStateUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AccountRoleStateUpsertOne.ID is not supported by MySQL driver. Use AccountRoleStateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountRoleStateUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountRoleStateCreateBulk is the builder for creating many AccountRoleState entities in bulk.
type AccountRoleStateCreateBulk struct {
	config
	err      error
	builders []*AccountRoleStateCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountRoleState entities in the database.
func (_c *AccountRoleStateCreateBulk) Save(ctx context.Context) ([]*AccountRoleState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountRoleState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountRoleStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountRoleStateCreateBulk) SaveX(ctx context.Context) []*AccountRoleState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountRoleStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountRoleStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountRoleState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountRoleStateUpsert) {
//			SetRevision(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountRoleStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountRoleStateUpsertBulk {
	_c.conflict = opts
	return &AccountRoleStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountRoleState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountRoleStateCreateBulk) OnConflictColumns(columns ...string) *AccountRoleStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountRoleStateUpsertBulk{
		create: _c,
	}
}

// AccountRoleStateUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountRoleState nodes.
type AccountRoleStateUpsertBulk struct {
	create *AccountRoleStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountRoleState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accountrolestate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountRoleStateUpsertBulk) UpdateNewValues() *AccountRoleStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(accountrolestate.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountRoleState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountRoleStateUpsertBulk) Ignore() *AccountRoleStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountRoleStateUpsertBulk) DoNothing() *AccountRoleStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountRoleStateCreateBulk.OnConflict
// documentation for more info.
func (u *AccountRoleStateUpsertBulk) Update(set func(*AccountRoleStateUpsert)) *AccountRoleStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountRoleStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetRevision sets the "revision" field.
func (u *AccountRoleStateUpsertBulk) SetRevision(v int64) *AccountRoleStateUpsertBulk {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *AccountRoleStateUpsertBulk) AddRevision(v int64) *AccountRoleStateUpsertBulk {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *AccountRoleStateUpsertBulk) UpdateRevision() *AccountRoleStateUpsertBulk {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.UpdateRevision()
	})
}

// SetAdminInitialized sets the "admin_initialized" field.
func (u *AccountRoleStateUpsertBulk) SetAdminInitialized(v bool) *AccountRoleStateUpsertBulk {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.SetAdminInitialized(v)
	})
}

// UpdateAdminInitialized sets the "admin_initialized" field to the value that was provided on create.
func (u *AccountRoleStateUpsertBulk) UpdateAdminInitialized() *AccountRoleStateUpsertBulk {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.UpdateAdminInitialized()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountRoleStateUpsertBulk) SetUpdatedAt(v time.Time) *AccountRoleStateUpsertBulk {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountRoleStateUpsertBulk) UpdateUpdatedAt() *AccountRoleStateUpsertBulk {
	return u.Update(func(s *AccountRoleStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountRoleStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountRoleStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountRoleStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountRoleStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
