// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eagle-go/eagle/internal/platform/database/ent/accountroleaudit"
	"github.com/eagle-go/eagle/internal/platform/database/ent/predicate"
)

// AccountRoleAuditDelete is the builder for deleting a AccountRoleAudit entity.
type AccountRoleAuditDelete struct {
	config
	hooks    []Hook
	mutation *AccountRoleAuditMutation
}

// Where appends a list predicates to the AccountRoleAuditDelete builder.
func (_d *AccountRoleAuditDelete) Where(ps ...predicate.AccountRoleAudit) *AccountRoleAuditDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountRoleAuditDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountRoleAuditDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountRoleAuditDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountroleaudit.Table, sqlgraph.NewFieldSpec(accountroleaudit.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountRoleAuditDeleteOne is the builder for deleting a single AccountRoleAudit entity.
type AccountRoleAuditDeleteOne struct {
	_d *AccountRoleAuditDelete
}

// Where appends a list predicates to the AccountRoleAuditDelete builder.
func (_d *AccountRoleAuditDeleteOne) Where(ps ...predicate.AccountRoleAudit) *AccountRoleAuditDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountRoleAuditDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountroleaudit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountRoleAuditDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
