// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eagle-go/eagle/internal/platform/database/ent/authusedcredential"
	"github.com/eagle-go/eagle/internal/platform/database/ent/predicate"
)

// AuthUsedCredentialUpdate is the builder for updating AuthUsedCredential entities.
type AuthUsedCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *AuthUsedCredentialMutation
}

// Where appends a list predicates to the AuthUsedCredentialUpdate builder.
func (_u *AuthUsedCredentialUpdate) Where(ps ...predicate.AuthUsedCredential) *AuthUsedCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthUsedCredentialUpdate) SetExpiresAt(v time.Time) *AuthUsedCredentialUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthUsedCredentialUpdate) SetNillableExpiresAt(v *time.Time) *AuthUsedCredentialUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the AuthUsedCredentialMutation object of the builder.
func (_u *AuthUsedCredentialUpdate) Mutation() *AuthUsedCredentialMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthUsedCredentialUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthUsedCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthUsedCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthUsedCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthUsedCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authusedcredential.Table, authusedcredential.Columns, sqlgraph.NewFieldSpec(authusedcredential.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authusedcredential.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authusedcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthUsedCredentialUpdateOne is the builder for updating a single AuthUsedCredential entity.
type AuthUsedCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthUsedCredentialMutation
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthUsedCredentialUpdateOne) SetExpiresAt(v time.Time) *AuthUsedCredentialUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthUsedCredentialUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthUsedCredentialUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the AuthUsedCredentialMutation object of the builder.
func (_u *AuthUsedCredentialUpdateOne) Mutation() *AuthUsedCredentialMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthUsedCredentialUpdate builder.
func (_u *AuthUsedCredentialUpdateOne) Where(ps ...predicate.AuthUsedCredential) *AuthUsedCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthUsedCredentialUpdateOne) Select(field string, fields ...string) *AuthUsedCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthUsedCredential entity.
func (_u *AuthUsedCredentialUpdateOne) Save(ctx context.Context) (*AuthUsedCredential, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthUsedCredentialUpdateOne) SaveX(ctx context.Context) *AuthUsedCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthUsedCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthUsedCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthUsedCredentialUpdateOne) sqlSave(ctx context.Context) (_node *AuthUsedCredential, err error) {
	_spec := sqlgraph.NewUpdateSpec(authusedcredential.Table, authusedcredential.Columns, sqlgraph.NewFieldSpec(authusedcredential.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthUsedCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authusedcredential.FieldID)
		for _, f := range fields {
			if !authusedcredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authusedcredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authusedcredential.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &AuthUsedCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authusedcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
