// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eagle-go/eagle/internal/platform/database/ent/useraccount"
)

// UserAccountCreate is the builder for creating a UserAccount entity.
type UserAccountCreate struct {
	config
	mutation *UserAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDisplayName sets the "display_name" field.
func (_c *UserAccountCreate) SetDisplayName(v string) *UserAccountCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableDisplayName(v *string) *UserAccountCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *UserAccountCreate) SetAvatarURL(v string) *UserAccountCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableAvatarURL(v *string) *UserAccountCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserAccountCreate) SetStatus(v int32) *UserAccountCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableStatus(v *int32) *UserAccountCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAccountCreate) SetCreatedAt(v time.Time) *UserAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableCreatedAt(v *time.Time) *UserAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAccountCreate) SetUpdatedAt(v time.Time) *UserAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAccountCreate) SetNillableUpdatedAt(v *time.Time) *UserAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserAccountCreate) SetID(v string) *UserAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UserAccountMutation object of the builder.
func (_c *UserAccountCreate) Mutation() *UserAccountMutation {
	return _c.mutation
}

// Save creates the UserAccount in the database.
func (_c *UserAccountCreate) Save(ctx context.Context) (*UserAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAccountCreate) SaveX(ctx context.Context) *UserAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAccountCreate) defaults() {
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := useraccount.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.AvatarURL(); !ok {
		v := useraccount.DefaultAvatarURL
		_c.mutation.SetAvatarURL(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := useraccount.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := useraccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := useraccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAccountCreate) check() error {
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "UserAccount.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := useraccount.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "UserAccount.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AvatarURL(); !ok {
		return &ValidationError{Name: "avatar_url", err: errors.New(`ent: missing required field "UserAccount.avatar_url"`)}
	}
	if v, ok := _c.mutation.AvatarURL(); ok {
		if err := useraccount.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "UserAccount.avatar_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserAccount.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAccount.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := useraccount.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "UserAccount.id": %w`, err)}
		}
	}
	return nil
}

func (_c *UserAccountCreate) sqlSave(ctx context.Context) (*UserAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UserAccount.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAccountCreate) createSpec() (*UserAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useraccount.Table, sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(useraccount.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(useraccount.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(useraccount.FieldStatus, field.TypeInt32, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useraccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(useraccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAccount.Create().
//		SetDisplayName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAccountUpsert) {
//			SetDisplayName(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAccountCreate) OnConflict(opts ...sql.ConflictOption) *UserAccountUpsertOne {
	_c.conflict = opts
	return &UserAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAccountCreate) OnConflictColumns(columns ...string) *UserAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAccountUpsertOne{
		create: _c,
	}
}

type (
	// UserAccountUpsertOne is the builder for "upsert"-ing
	//  one UserAccount node.
	UserAccountUpsertOne struct {
		create *UserAccountCreate
	}

	// UserAccountUpsert is the "OnConflict" setter.
	UserAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetDisplayName sets the "display_name" field.
func (u *UserAccountUpsert) SetDisplayName(v string) *UserAccountUpsert {
	u.Set(useraccount.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *UserAccountUpsert) UpdateDisplayName() *UserAccountUpsert {
	u.SetExcluded(useraccount.FieldDisplayName)
	return u
}

// SetAvatarURL sets the "avatar_url" field.
func (u *UserAccountUpsert) SetAvatarURL(v string) *UserAccountUpsert {
	u.Set(useraccount.FieldAvatarURL, v)
	return u
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *UserAccountUpsert) UpdateAvatarURL() *UserAccountUpsert {
	u.SetExcluded(useraccount.FieldAvatarURL)
	return u
}

// SetStatus sets the "status" field.
func (u *UserAccountUpsert) SetStatus(v int32) *UserAccountUpsert {
	u.Set(useraccount.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserAccountUpsert) UpdateStatus() *UserAccountUpsert {
	u.SetExcluded(useraccount.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *UserAccountUpsert) AddStatus(v int32) *UserAccountUpsert {
	u.Add(useraccount.FieldStatus, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAccountUpsert) SetUpdatedAt(v time.Time) *UserAccountUpsert {
	u.Set(useraccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAccountUpsert) UpdateUpdatedAt() *UserAccountUpsert {
	u.SetExcluded(useraccount.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UserAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(useraccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserAccountUpsertOne) UpdateNewValues() *UserAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(useraccount.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(useraccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserAccountUpsertOne) Ignore() *UserAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAccountUpsertOne) DoNothing() *UserAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAccountCreate.OnConflict
// documentation for more info.
func (u *UserAccountUpsertOne) Update(set func(*UserAccountUpsert)) *UserAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *UserAccountUpsertOne) SetDisplayName(v string) *UserAccountUpsertOne {
	return u.Update(func(s *UserAccountUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *UserAccountUpsertOne) UpdateDisplayName() *UserAccountUpsertOne {
	return u.Update(func(s *UserAccountUpsert) {
		s.UpdateDisplayName()
	})
}

// SetAvatarURL sets the "avatar_url" field.
func (u *UserAccountUpsertOne) SetAvatarURL(v string) *UserAccountUpsertOne {
	return u.Update(func(s *UserAccountUpsert) {
		s.SetAvatarURL(v)
	})
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *UserAccountUpsertOne) UpdateAvatarURL() *UserAccountUpsertOne {
	return u.Update(func(s *UserAccountUpsert) {
		s.UpdateAvatarURL()
	})
}

// SetStatus sets the "status" field.
func (u *UserAccountUpsertOne) SetStatus(v int32) *UserAccountUpsertOne {
	return u.Update(func(s *UserAccountUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *UserAccountUpsertOne) AddStatus(v int32) *UserAccountUpsertOne {
	return u.Update(func(s *UserAccountUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserAccountUpsertOne) UpdateStatus() *UserAccountUpsertOne {
	return u.Update(func(s *UserAccountUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAccountUpsertOne) SetUpdatedAt(v time.Time) *UserAccountUpsertOne {
	return u.Update(func(s *UserAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAccountUpsertOne) UpdateUpdatedAt() *UserAccountUpsertOne {
	return u.Update(func(s *UserAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserAccountUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UserAccountUpsertOne.ID is not supported by MySQL driver. Use UserAccountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserAccountUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserAccountCreateBulk is the builder for creating many UserAccount entities in bulk.
type UserAccountCreateBulk struct {
	config
	err      error
	builders []*UserAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the UserAccount entities in the database.
func (_c *UserAccountCreateBulk) Save(ctx context.Context) ([]*UserAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAccountCreateBulk) SaveX(ctx context.Context) []*UserAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserAccountUpsert) {
//			SetDisplayName(v+v).
//		}).
//		Exec(ctx)
func (_c *UserAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserAccountUpsertBulk {
	_c.conflict = opts
	return &UserAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserAccountCreateBulk) OnConflictColumns(columns ...string) *UserAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserAccountUpsertBulk{
		create: _c,
	}
}

// UserAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of UserAccount nodes.
type UserAccountUpsertBulk struct {
	create *UserAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(useraccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserAccountUpsertBulk) UpdateNewValues() *UserAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(useraccount.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(useraccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserAccountUpsertBulk) Ignore() *UserAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserAccountUpsertBulk) DoNothing() *UserAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserAccountCreateBulk.OnConflict
// documentation for more info.
func (u *UserAccountUpsertBulk) Update(set func(*UserAccountUpsert)) *UserAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *UserAccountUpsertBulk) SetDisplayName(v string) *UserAccountUpsertBulk {
	return u.Update(func(s *UserAccountUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *UserAccountUpsertBulk) UpdateDisplayName() *UserAccountUpsertBulk {
	return u.Update(func(s *UserAccountUpsert) {
		s.UpdateDisplayName()
	})
}

// SetAvatarURL sets the "avatar_url" field.
func (u *UserAccountUpsertBulk) SetAvatarURL(v string) *UserAccountUpsertBulk {
	return u.Update(func(s *UserAccountUpsert) {
		s.SetAvatarURL(v)
	})
}

// UpdateAvatarURL sets the "avatar_url" field to the value that was provided on create.
func (u *UserAccountUpsertBulk) UpdateAvatarURL() *UserAccountUpsertBulk {
	return u.Update(func(s *UserAccountUpsert) {
		s.UpdateAvatarURL()
	})
}

// SetStatus sets the "status" field.
func (u *UserAccountUpsertBulk) SetStatus(v int32) *UserAccountUpsertBulk {
	return u.Update(func(s *UserAccountUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *UserAccountUpsertBulk) AddStatus(v int32) *UserAccountUpsertBulk {
	return u.Update(func(s *UserAccountUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserAccountUpsertBulk) UpdateStatus() *UserAccountUpsertBulk {
	return u.Update(func(s *UserAccountUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserAccountUpsertBulk) SetUpdatedAt(v time.Time) *UserAccountUpsertBulk {
	return u.Update(func(s *UserAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserAccountUpsertBulk) UpdateUpdatedAt() *UserAccountUpsertBulk {
	return u.Update(func(s *UserAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
