// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/eagle-go/eagle/app/order/internal/platform/database/ent/orderitem"
	"github.com/eagle-go/eagle/app/order/internal/platform/database/ent/outboxevent"
	"github.com/eagle-go/eagle/app/order/internal/platform/database/ent/predicate"
	"github.com/eagle-go/eagle/app/order/internal/platform/database/ent/purchaseorder"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeOrderItem     = "OrderItem"
	TypeOutboxEvent   = "OutboxEvent"
	TypePurchaseOrder = "PurchaseOrder"
)

// OrderItemMutation represents an operation that mutates the OrderItem nodes in the graph.
type OrderItemMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int
	order_id            *string
	product_id          *int64
	addproduct_id       *int64
	product_sku         *string
	product_name        *string
	unit_price_cents    *int64
	addunit_price_cents *int64
	quantity            *int32
	addquantity         *int32
	subtotal_cents      *int64
	addsubtotal_cents   *int64
	clearedFields       map[string]struct{}
	done                bool
	oldValue            func(context.Context) (*OrderItem, error)
	predicates          []predicate.OrderItem
}

var _ ent.Mutation = (*OrderItemMutation)(nil)

// orderitemOption allows management of the mutation configuration using functional options.
type orderitemOption func(*OrderItemMutation)

// newOrderItemMutation creates new mutation for the OrderItem entity.
func newOrderItemMutation(c config, op Op, opts ...orderitemOption) *OrderItemMutation {
	m := &OrderItemMutation{
		config:        c,
		op:            op,
		typ:           TypeOrderItem,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withOrderItemID sets the ID field of the mutation.
func withOrderItemID(id int) orderitemOption {
	return func(m *OrderItemMutation) {
		var (
			err   error
			once  sync.Once
			value *OrderItem
		)
		m.oldValue = func(ctx context.Context) (*OrderItem, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().OrderItem.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withOrderItem sets the old OrderItem of the mutation.
func withOrderItem(node *OrderItem) orderitemOption {
	return func(m *OrderItemMutation) {
		m.oldValue = func(context.Context) (*OrderItem, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m OrderItemMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m OrderItemMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *OrderItemMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *OrderItemMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().OrderItem.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetOrderID sets the "order_id" field.
func (m *OrderItemMutation) SetOrderID(s string) {
	m.order_id = &s
}

// OrderID returns the value of the "order_id" field in the mutation.
func (m *OrderItemMutation) OrderID() (r string, exists bool) {
	v := m.order_id
	if v == nil {
		return
	}
	return *v, true
}

// OldOrderID returns the old "order_id" field's value of the OrderItem entity.
// If the OrderItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderItemMutation) OldOrderID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOrderID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOrderID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOrderID: %w", err)
	}
	return oldValue.OrderID, nil
}

// ResetOrderID resets all changes to the "order_id" field.
func (m *OrderItemMutation) ResetOrderID() {
	m.order_id = nil
}

// SetProductID sets the "product_id" field.
func (m *OrderItemMutation) SetProductID(i int64) {
	m.product_id = &i
	m.addproduct_id = nil
}

// ProductID returns the value of the "product_id" field in the mutation.
func (m *OrderItemMutation) ProductID() (r int64, exists bool) {
	v := m.product_id
	if v == nil {
		return
	}
	return *v, true
}

// OldProductID returns the old "product_id" field's value of the OrderItem entity.
// If the OrderItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderItemMutation) OldProductID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProductID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProductID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProductID: %w", err)
	}
	return oldValue.ProductID, nil
}

// AddProductID adds i to the "product_id" field.
func (m *OrderItemMutation) AddProductID(i int64) {
	if m.addproduct_id != nil {
		*m.addproduct_id += i
	} else {
		m.addproduct_id = &i
	}
}

// AddedProductID returns the value that was added to the "product_id" field in this mutation.
func (m *OrderItemMutation) AddedProductID() (r int64, exists bool) {
	v := m.addproduct_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetProductID resets all changes to the "product_id" field.
func (m *OrderItemMutation) ResetProductID() {
	m.product_id = nil
	m.addproduct_id = nil
}

// SetProductSku sets the "product_sku" field.
func (m *OrderItemMutation) SetProductSku(s string) {
	m.product_sku = &s
}

// ProductSku returns the value of the "product_sku" field in the mutation.
func (m *OrderItemMutation) ProductSku() (r string, exists bool) {
	v := m.product_sku
	if v == nil {
		return
	}
	return *v, true
}

// OldProductSku returns the old "product_sku" field's value of the OrderItem entity.
// If the OrderItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderItemMutation) OldProductSku(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProductSku is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProductSku requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProductSku: %w", err)
	}
	return oldValue.ProductSku, nil
}

// ResetProductSku resets all changes to the "product_sku" field.
func (m *OrderItemMutation) ResetProductSku() {
	m.product_sku = nil
}

// SetProductName sets the "product_name" field.
func (m *OrderItemMutation) SetProductName(s string) {
	m.product_name = &s
}

// ProductName returns the value of the "product_name" field in the mutation.
func (m *OrderItemMutation) ProductName() (r string, exists bool) {
	v := m.product_name
	if v == nil {
		return
	}
	return *v, true
}

// OldProductName returns the old "product_name" field's value of the OrderItem entity.
// If the OrderItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderItemMutation) OldProductName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProductName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProductName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProductName: %w", err)
	}
	return oldValue.ProductName, nil
}

// ResetProductName resets all changes to the "product_name" field.
func (m *OrderItemMutation) ResetProductName() {
	m.product_name = nil
}

// SetUnitPriceCents sets the "unit_price_cents" field.
func (m *OrderItemMutation) SetUnitPriceCents(i int64) {
	m.unit_price_cents = &i
	m.addunit_price_cents = nil
}

// UnitPriceCents returns the value of the "unit_price_cents" field in the mutation.
func (m *OrderItemMutation) UnitPriceCents() (r int64, exists bool) {
	v := m.unit_price_cents
	if v == nil {
		return
	}
	return *v, true
}

// OldUnitPriceCents returns the old "unit_price_cents" field's value of the OrderItem entity.
// If the OrderItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderItemMutation) OldUnitPriceCents(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUnitPriceCents is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUnitPriceCents requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUnitPriceCents: %w", err)
	}
	return oldValue.UnitPriceCents, nil
}

// AddUnitPriceCents adds i to the "unit_price_cents" field.
func (m *OrderItemMutation) AddUnitPriceCents(i int64) {
	if m.addunit_price_cents != nil {
		*m.addunit_price_cents += i
	} else {
		m.addunit_price_cents = &i
	}
}

// AddedUnitPriceCents returns the value that was added to the "unit_price_cents" field in this mutation.
func (m *OrderItemMutation) AddedUnitPriceCents() (r int64, exists bool) {
	v := m.addunit_price_cents
	if v == nil {
		return
	}
	return *v, true
}

// ResetUnitPriceCents resets all changes to the "unit_price_cents" field.
func (m *OrderItemMutation) ResetUnitPriceCents() {
	m.unit_price_cents = nil
	m.addunit_price_cents = nil
}

// SetQuantity sets the "quantity" field.
func (m *OrderItemMutation) SetQuantity(i int32) {
	m.quantity = &i
	m.addquantity = nil
}

// Quantity returns the value of the "quantity" field in the mutation.
func (m *OrderItemMutation) Quantity() (r int32, exists bool) {
	v := m.quantity
	if v == nil {
		return
	}
	return *v, true
}

// OldQuantity returns the old "quantity" field's value of the OrderItem entity.
// If the OrderItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderItemMutation) OldQuantity(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldQuantity is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldQuantity requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldQuantity: %w", err)
	}
	return oldValue.Quantity, nil
}

// AddQuantity adds i to the "quantity" field.
func (m *OrderItemMutation) AddQuantity(i int32) {
	if m.addquantity != nil {
		*m.addquantity += i
	} else {
		m.addquantity = &i
	}
}

// AddedQuantity returns the value that was added to the "quantity" field in this mutation.
func (m *OrderItemMutation) AddedQuantity() (r int32, exists bool) {
	v := m.addquantity
	if v == nil {
		return
	}
	return *v, true
}

// ResetQuantity resets all changes to the "quantity" field.
func (m *OrderItemMutation) ResetQuantity() {
	m.quantity = nil
	m.addquantity = nil
}

// SetSubtotalCents sets the "subtotal_cents" field.
func (m *OrderItemMutation) SetSubtotalCents(i int64) {
	m.subtotal_cents = &i
	m.addsubtotal_cents = nil
}

// SubtotalCents returns the value of the "subtotal_cents" field in the mutation.
func (m *OrderItemMutation) SubtotalCents() (r int64, exists bool) {
	v := m.subtotal_cents
	if v == nil {
		return
	}
	return *v, true
}

// OldSubtotalCents returns the old "subtotal_cents" field's value of the OrderItem entity.
// If the OrderItem object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OrderItemMutation) OldSubtotalCents(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSubtotalCents is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSubtotalCents requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSubtotalCents: %w", err)
	}
	return oldValue.SubtotalCents, nil
}

// AddSubtotalCents adds i to the "subtotal_cents" field.
func (m *OrderItemMutation) AddSubtotalCents(i int64) {
	if m.addsubtotal_cents != nil {
		*m.addsubtotal_cents += i
	} else {
		m.addsubtotal_cents = &i
	}
}

// AddedSubtotalCents returns the value that was added to the "subtotal_cents" field in this mutation.
func (m *OrderItemMutation) AddedSubtotalCents() (r int64, exists bool) {
	v := m.addsubtotal_cents
	if v == nil {
		return
	}
	return *v, true
}

// ResetSubtotalCents resets all changes to the "subtotal_cents" field.
func (m *OrderItemMutation) ResetSubtotalCents() {
	m.subtotal_cents = nil
	m.addsubtotal_cents = nil
}

// Where appends a list predicates to the OrderItemMutation builder.
func (m *OrderItemMutation) Where(ps ...predicate.OrderItem) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the OrderItemMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *OrderItemMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.OrderItem, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *OrderItemMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *OrderItemMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (OrderItem).
func (m *OrderItemMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *OrderItemMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.order_id != nil {
		fields = append(fields, orderitem.FieldOrderID)
	}
	if m.product_id != nil {
		fields = append(fields, orderitem.FieldProductID)
	}
	if m.product_sku != nil {
		fields = append(fields, orderitem.FieldProductSku)
	}
	if m.product_name != nil {
		fields = append(fields, orderitem.FieldProductName)
	}
	if m.unit_price_cents != nil {
		fields = append(fields, orderitem.FieldUnitPriceCents)
	}
	if m.quantity != nil {
		fields = append(fields, orderitem.FieldQuantity)
	}
	if m.subtotal_cents != nil {
		fields = append(fields, orderitem.FieldSubtotalCents)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *OrderItemMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case orderitem.FieldOrderID:
		return m.OrderID()
	case orderitem.FieldProductID:
		return m.ProductID()
	case orderitem.FieldProductSku:
		return m.ProductSku()
	case orderitem.FieldProductName:
		return m.ProductName()
	case orderitem.FieldUnitPriceCents:
		return m.UnitPriceCents()
	case orderitem.FieldQuantity:
		return m.Quantity()
	case orderitem.FieldSubtotalCents:
		return m.SubtotalCents()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *OrderItemMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case orderitem.FieldOrderID:
		return m.OldOrderID(ctx)
	case orderitem.FieldProductID:
		return m.OldProductID(ctx)
	case orderitem.FieldProductSku:
		return m.OldProductSku(ctx)
	case orderitem.FieldProductName:
		return m.OldProductName(ctx)
	case orderitem.FieldUnitPriceCents:
		return m.OldUnitPriceCents(ctx)
	case orderitem.FieldQuantity:
		return m.OldQuantity(ctx)
	case orderitem.FieldSubtotalCents:
		return m.OldSubtotalCents(ctx)
	}
	return nil, fmt.Errorf("unknown OrderItem field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OrderItemMutation) SetField(name string, value ent.Value) error {
	switch name {
	case orderitem.FieldOrderID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOrderID(v)
		return nil
	case orderitem.FieldProductID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProductID(v)
		return nil
	case orderitem.FieldProductSku:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProductSku(v)
		return nil
	case orderitem.FieldProductName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProductName(v)
		return nil
	case orderitem.FieldUnitPriceCents:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUnitPriceCents(v)
		return nil
	case orderitem.FieldQuantity:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetQuantity(v)
		return nil
	case orderitem.FieldSubtotalCents:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSubtotalCents(v)
		return nil
	}
	return fmt.Errorf("unknown OrderItem field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *OrderItemMutation) AddedFields() []string {
	var fields []string
	if m.addproduct_id != nil {
		fields = append(fields, orderitem.FieldProductID)
	}
	if m.addunit_price_cents != nil {
		fields = append(fields, orderitem.FieldUnitPriceCents)
	}
	if m.addquantity != nil {
		fields = append(fields, orderitem.FieldQuantity)
	}
	if m.addsubtotal_cents != nil {
		fields = append(fields, orderitem.FieldSubtotalCents)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *OrderItemMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case orderitem.FieldProductID:
		return m.AddedProductID()
	case orderitem.FieldUnitPriceCents:
		return m.AddedUnitPriceCents()
	case orderitem.FieldQuantity:
		return m.AddedQuantity()
	case orderitem.FieldSubtotalCents:
		return m.AddedSubtotalCents()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OrderItemMutation) AddField(name string, value ent.Value) error {
	switch name {
	case orderitem.FieldProductID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddProductID(v)
		return nil
	case orderitem.FieldUnitPriceCents:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUnitPriceCents(v)
		return nil
	case orderitem.FieldQuantity:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddQuantity(v)
		return nil
	case orderitem.FieldSubtotalCents:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSubtotalCents(v)
		return nil
	}
	return fmt.Errorf("unknown OrderItem numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *OrderItemMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *OrderItemMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *OrderItemMutation) ClearField(name string) error {
	return fmt.Errorf("unknown OrderItem nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *OrderItemMutation) ResetField(name string) error {
	switch name {
	case orderitem.FieldOrderID:
		m.ResetOrderID()
		return nil
	case orderitem.FieldProductID:
		m.ResetProductID()
		return nil
	case orderitem.FieldProductSku:
		m.ResetProductSku()
		return nil
	case orderitem.FieldProductName:
		m.ResetProductName()
		return nil
	case orderitem.FieldUnitPriceCents:
		m.ResetUnitPriceCents()
		return nil
	case orderitem.FieldQuantity:
		m.ResetQuantity()
		return nil
	case orderitem.FieldSubtotalCents:
		m.ResetSubtotalCents()
		return nil
	}
	return fmt.Errorf("unknown OrderItem field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *OrderItemMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *OrderItemMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *OrderItemMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *OrderItemMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *OrderItemMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *OrderItemMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *OrderItemMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown OrderItem unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *OrderItemMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown OrderItem edge %s", name)
}

// OutboxEventMutation represents an operation that mutates the OutboxEvent nodes in the graph.
type OutboxEventMutation struct {
	config
	op            Op
	typ           string
	id            *string
	aggregate_id  *string
	event_type    *string
	routing_key   *string
	payload       *[]byte
	attempts      *int32
	addattempts   *int32
	last_error    *string
	available_at  *time.Time
	locked_until  *time.Time
	published_at  *time.Time
	failed_at     *time.Time
	created_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*OutboxEvent, error)
	predicates    []predicate.OutboxEvent
}

var _ ent.Mutation = (*OutboxEventMutation)(nil)

// outboxeventOption allows management of the mutation configuration using functional options.
type outboxeventOption func(*OutboxEventMutation)

// newOutboxEventMutation creates new mutation for the OutboxEvent entity.
func newOutboxEventMutation(c config, op Op, opts ...outboxeventOption) *OutboxEventMutation {
	m := &OutboxEventMutation{
		config:        c,
		op:            op,
		typ:           TypeOutboxEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withOutboxEventID sets the ID field of the mutation.
func withOutboxEventID(id string) outboxeventOption {
	return func(m *OutboxEventMutation) {
		var (
			err   error
			once  sync.Once
			value *OutboxEvent
		)
		m.oldValue = func(ctx context.Context) (*OutboxEvent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().OutboxEvent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withOutboxEvent sets the old OutboxEvent of the mutation.
func withOutboxEvent(node *OutboxEvent) outboxeventOption {
	return func(m *OutboxEventMutation) {
		m.oldValue = func(context.Context) (*OutboxEvent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m OutboxEventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m OutboxEventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of OutboxEvent entities.
func (m *OutboxEventMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *OutboxEventMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *OutboxEventMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().OutboxEvent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetAggregateID sets the "aggregate_id" field.
func (m *OutboxEventMutation) SetAggregateID(s string) {
	m.aggregate_id = &s
}

// AggregateID returns the value of the "aggregate_id" field in the mutation.
func (m *OutboxEventMutation) AggregateID() (r string, exists bool) {
	v := m.aggregate_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAggregateID returns the old "aggregate_id" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldAggregateID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAggregateID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAggregateID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAggregateID: %w", err)
	}
	return oldValue.AggregateID, nil
}

// ResetAggregateID resets all changes to the "aggregate_id" field.
func (m *OutboxEventMutation) ResetAggregateID() {
	m.aggregate_id = nil
}

// SetEventType sets the "event_type" field.
func (m *OutboxEventMutation) SetEventType(s string) {
	m.event_type = &s
}

// EventType returns the value of the "event_type" field in the mutation.
func (m *OutboxEventMutation) EventType() (r string, exists bool) {
	v := m.event_type
	if v == nil {
		return
	}
	return *v, true
}

// OldEventType returns the old "event_type" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldEventType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEventType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEventType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEventType: %w", err)
	}
	return oldValue.EventType, nil
}

// ResetEventType resets all changes to the "event_type" field.
func (m *OutboxEventMutation) ResetEventType() {
	m.event_type = nil
}

// SetRoutingKey sets the "routing_key" field.
func (m *OutboxEventMutation) SetRoutingKey(s string) {
	m.routing_key = &s
}

// RoutingKey returns the value of the "routing_key" field in the mutation.
func (m *OutboxEventMutation) RoutingKey() (r string, exists bool) {
	v := m.routing_key
	if v == nil {
		return
	}
	return *v, true
}

// OldRoutingKey returns the old "routing_key" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldRoutingKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRoutingKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRoutingKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRoutingKey: %w", err)
	}
	return oldValue.RoutingKey, nil
}

// ResetRoutingKey resets all changes to the "routing_key" field.
func (m *OutboxEventMutation) ResetRoutingKey() {
	m.routing_key = nil
}

// SetPayload sets the "payload" field.
func (m *OutboxEventMutation) SetPayload(b []byte) {
	m.payload = &b
}

// Payload returns the value of the "payload" field in the mutation.
func (m *OutboxEventMutation) Payload() (r []byte, exists bool) {
	v := m.payload
	if v == nil {
		return
	}
	return *v, true
}

// OldPayload returns the old "payload" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldPayload(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPayload is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPayload requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPayload: %w", err)
	}
	return oldValue.Payload, nil
}

// ResetPayload resets all changes to the "payload" field.
func (m *OutboxEventMutation) ResetPayload() {
	m.payload = nil
}

// SetAttempts sets the "attempts" field.
func (m *OutboxEventMutation) SetAttempts(i int32) {
	m.attempts = &i
	m.addattempts = nil
}

// Attempts returns the value of the "attempts" field in the mutation.
func (m *OutboxEventMutation) Attempts() (r int32, exists bool) {
	v := m.attempts
	if v == nil {
		return
	}
	return *v, true
}

// OldAttempts returns the old "attempts" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldAttempts(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAttempts is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAttempts requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAttempts: %w", err)
	}
	return oldValue.Attempts, nil
}

// AddAttempts adds i to the "attempts" field.
func (m *OutboxEventMutation) AddAttempts(i int32) {
	if m.addattempts != nil {
		*m.addattempts += i
	} else {
		m.addattempts = &i
	}
}

// AddedAttempts returns the value that was added to the "attempts" field in this mutation.
func (m *OutboxEventMutation) AddedAttempts() (r int32, exists bool) {
	v := m.addattempts
	if v == nil {
		return
	}
	return *v, true
}

// ResetAttempts resets all changes to the "attempts" field.
func (m *OutboxEventMutation) ResetAttempts() {
	m.attempts = nil
	m.addattempts = nil
}

// SetLastError sets the "last_error" field.
func (m *OutboxEventMutation) SetLastError(s string) {
	m.last_error = &s
}

// LastError returns the value of the "last_error" field in the mutation.
func (m *OutboxEventMutation) LastError() (r string, exists bool) {
	v := m.last_error
	if v == nil {
		return
	}
	return *v, true
}

// OldLastError returns the old "last_error" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldLastError(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastError is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastError requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastError: %w", err)
	}
	return oldValue.LastError, nil
}

// ResetLastError resets all changes to the "last_error" field.
func (m *OutboxEventMutation) ResetLastError() {
	m.last_error = nil
}

// SetAvailableAt sets the "available_at" field.
func (m *OutboxEventMutation) SetAvailableAt(t time.Time) {
	m.available_at = &t
}

// AvailableAt returns the value of the "available_at" field in the mutation.
func (m *OutboxEventMutation) AvailableAt() (r time.Time, exists bool) {
	v := m.available_at
	if v == nil {
		return
	}
	return *v, true
}

// OldAvailableAt returns the old "available_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldAvailableAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAvailableAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAvailableAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAvailableAt: %w", err)
	}
	return oldValue.AvailableAt, nil
}

// ResetAvailableAt resets all changes to the "available_at" field.
func (m *OutboxEventMutation) ResetAvailableAt() {
	m.available_at = nil
}

// SetLockedUntil sets the "locked_until" field.
func (m *OutboxEventMutation) SetLockedUntil(t time.Time) {
	m.locked_until = &t
}

// LockedUntil returns the value of the "locked_until" field in the mutation.
func (m *OutboxEventMutation) LockedUntil() (r time.Time, exists bool) {
	v := m.locked_until
	if v == nil {
		return
	}
	return *v, true
}

// OldLockedUntil returns the old "locked_until" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldLockedUntil(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLockedUntil is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLockedUntil requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLockedUntil: %w", err)
	}
	return oldValue.LockedUntil, nil
}

// ClearLockedUntil clears the value of the "locked_until" field.
func (m *OutboxEventMutation) ClearLockedUntil() {
	m.locked_until = nil
	m.clearedFields[outboxevent.FieldLockedUntil] = struct{}{}
}

// LockedUntilCleared returns if the "locked_until" field was cleared in this mutation.
func (m *OutboxEventMutation) LockedUntilCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldLockedUntil]
	return ok
}

// ResetLockedUntil resets all changes to the "locked_until" field.
func (m *OutboxEventMutation) ResetLockedUntil() {
	m.locked_until = nil
	delete(m.clearedFields, outboxevent.FieldLockedUntil)
}

// SetPublishedAt sets the "published_at" field.
func (m *OutboxEventMutation) SetPublishedAt(t time.Time) {
	m.published_at = &t
}

// PublishedAt returns the value of the "published_at" field in the mutation.
func (m *OutboxEventMutation) PublishedAt() (r time.Time, exists bool) {
	v := m.published_at
	if v == nil {
		return
	}
	return *v, true
}

// OldPublishedAt returns the old "published_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldPublishedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublishedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublishedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublishedAt: %w", err)
	}
	return oldValue.PublishedAt, nil
}

// ClearPublishedAt clears the value of the "published_at" field.
func (m *OutboxEventMutation) ClearPublishedAt() {
	m.published_at = nil
	m.clearedFields[outboxevent.FieldPublishedAt] = struct{}{}
}

// PublishedAtCleared returns if the "published_at" field was cleared in this mutation.
func (m *OutboxEventMutation) PublishedAtCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldPublishedAt]
	return ok
}

// ResetPublishedAt resets all changes to the "published_at" field.
func (m *OutboxEventMutation) ResetPublishedAt() {
	m.published_at = nil
	delete(m.clearedFields, outboxevent.FieldPublishedAt)
}

// SetFailedAt sets the "failed_at" field.
func (m *OutboxEventMutation) SetFailedAt(t time.Time) {
	m.failed_at = &t
}

// FailedAt returns the value of the "failed_at" field in the mutation.
func (m *OutboxEventMutation) FailedAt() (r time.Time, exists bool) {
	v := m.failed_at
	if v == nil {
		return
	}
	return *v, true
}

// OldFailedAt returns the old "failed_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldFailedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFailedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFailedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFailedAt: %w", err)
	}
	return oldValue.FailedAt, nil
}

// ClearFailedAt clears the value of the "failed_at" field.
func (m *OutboxEventMutation) ClearFailedAt() {
	m.failed_at = nil
	m.clearedFields[outboxevent.FieldFailedAt] = struct{}{}
}

// FailedAtCleared returns if the "failed_at" field was cleared in this mutation.
func (m *OutboxEventMutation) FailedAtCleared() bool {
	_, ok := m.clearedFields[outboxevent.FieldFailedAt]
	return ok
}

// ResetFailedAt resets all changes to the "failed_at" field.
func (m *OutboxEventMutation) ResetFailedAt() {
	m.failed_at = nil
	delete(m.clearedFields, outboxevent.FieldFailedAt)
}

// SetCreatedAt sets the "created_at" field.
func (m *OutboxEventMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *OutboxEventMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the OutboxEvent entity.
// If the OutboxEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *OutboxEventMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *OutboxEventMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the OutboxEventMutation builder.
func (m *OutboxEventMutation) Where(ps ...predicate.OutboxEvent) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the OutboxEventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *OutboxEventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.OutboxEvent, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *OutboxEventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *OutboxEventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (OutboxEvent).
func (m *OutboxEventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *OutboxEventMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.aggregate_id != nil {
		fields = append(fields, outboxevent.FieldAggregateID)
	}
	if m.event_type != nil {
		fields = append(fields, outboxevent.FieldEventType)
	}
	if m.routing_key != nil {
		fields = append(fields, outboxevent.FieldRoutingKey)
	}
	if m.payload != nil {
		fields = append(fields, outboxevent.FieldPayload)
	}
	if m.attempts != nil {
		fields = append(fields, outboxevent.FieldAttempts)
	}
	if m.last_error != nil {
		fields = append(fields, outboxevent.FieldLastError)
	}
	if m.available_at != nil {
		fields = append(fields, outboxevent.FieldAvailableAt)
	}
	if m.locked_until != nil {
		fields = append(fields, outboxevent.FieldLockedUntil)
	}
	if m.published_at != nil {
		fields = append(fields, outboxevent.FieldPublishedAt)
	}
	if m.failed_at != nil {
		fields = append(fields, outboxevent.FieldFailedAt)
	}
	if m.created_at != nil {
		fields = append(fields, outboxevent.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *OutboxEventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case outboxevent.FieldAggregateID:
		return m.AggregateID()
	case outboxevent.FieldEventType:
		return m.EventType()
	case outboxevent.FieldRoutingKey:
		return m.RoutingKey()
	case outboxevent.FieldPayload:
		return m.Payload()
	case outboxevent.FieldAttempts:
		return m.Attempts()
	case outboxevent.FieldLastError:
		return m.LastError()
	case outboxevent.FieldAvailableAt:
		return m.AvailableAt()
	case outboxevent.FieldLockedUntil:
		return m.LockedUntil()
	case outboxevent.FieldPublishedAt:
		return m.PublishedAt()
	case outboxevent.FieldFailedAt:
		return m.FailedAt()
	case outboxevent.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *OutboxEventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case outboxevent.FieldAggregateID:
		return m.OldAggregateID(ctx)
	case outboxevent.FieldEventType:
		return m.OldEventType(ctx)
	case outboxevent.FieldRoutingKey:
		return m.OldRoutingKey(ctx)
	case outboxevent.FieldPayload:
		return m.OldPayload(ctx)
	case outboxevent.FieldAttempts:
		return m.OldAttempts(ctx)
	case outboxevent.FieldLastError:
		return m.OldLastError(ctx)
	case outboxevent.FieldAvailableAt:
		return m.OldAvailableAt(ctx)
	case outboxevent.FieldLockedUntil:
		return m.OldLockedUntil(ctx)
	case outboxevent.FieldPublishedAt:
		return m.OldPublishedAt(ctx)
	case outboxevent.FieldFailedAt:
		return m.OldFailedAt(ctx)
	case outboxevent.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown OutboxEvent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OutboxEventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case outboxevent.FieldAggregateID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAggregateID(v)
		return nil
	case outboxevent.FieldEventType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEventType(v)
		return nil
	case outboxevent.FieldRoutingKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRoutingKey(v)
		return nil
	case outboxevent.FieldPayload:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPayload(v)
		return nil
	case outboxevent.FieldAttempts:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAttempts(v)
		return nil
	case outboxevent.FieldLastError:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastError(v)
		return nil
	case outboxevent.FieldAvailableAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAvailableAt(v)
		return nil
	case outboxevent.FieldLockedUntil:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLockedUntil(v)
		return nil
	case outboxevent.FieldPublishedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublishedAt(v)
		return nil
	case outboxevent.FieldFailedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFailedAt(v)
		return nil
	case outboxevent.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *OutboxEventMutation) AddedFields() []string {
	var fields []string
	if m.addattempts != nil {
		fields = append(fields, outboxevent.FieldAttempts)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *OutboxEventMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case outboxevent.FieldAttempts:
		return m.AddedAttempts()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *OutboxEventMutation) AddField(name string, value ent.Value) error {
	switch name {
	case outboxevent.FieldAttempts:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAttempts(v)
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *OutboxEventMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(outboxevent.FieldLockedUntil) {
		fields = append(fields, outboxevent.FieldLockedUntil)
	}
	if m.FieldCleared(outboxevent.FieldPublishedAt) {
		fields = append(fields, outboxevent.FieldPublishedAt)
	}
	if m.FieldCleared(outboxevent.FieldFailedAt) {
		fields = append(fields, outboxevent.FieldFailedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *OutboxEventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *OutboxEventMutation) ClearField(name string) error {
	switch name {
	case outboxevent.FieldLockedUntil:
		m.ClearLockedUntil()
		return nil
	case outboxevent.FieldPublishedAt:
		m.ClearPublishedAt()
		return nil
	case outboxevent.FieldFailedAt:
		m.ClearFailedAt()
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *OutboxEventMutation) ResetField(name string) error {
	switch name {
	case outboxevent.FieldAggregateID:
		m.ResetAggregateID()
		return nil
	case outboxevent.FieldEventType:
		m.ResetEventType()
		return nil
	case outboxevent.FieldRoutingKey:
		m.ResetRoutingKey()
		return nil
	case outboxevent.FieldPayload:
		m.ResetPayload()
		return nil
	case outboxevent.FieldAttempts:
		m.ResetAttempts()
		return nil
	case outboxevent.FieldLastError:
		m.ResetLastError()
		return nil
	case outboxevent.FieldAvailableAt:
		m.ResetAvailableAt()
		return nil
	case outboxevent.FieldLockedUntil:
		m.ResetLockedUntil()
		return nil
	case outboxevent.FieldPublishedAt:
		m.ResetPublishedAt()
		return nil
	case outboxevent.FieldFailedAt:
		m.ResetFailedAt()
		return nil
	case outboxevent.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown OutboxEvent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *OutboxEventMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *OutboxEventMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *OutboxEventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *OutboxEventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *OutboxEventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *OutboxEventMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *OutboxEventMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown OutboxEvent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *OutboxEventMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown OutboxEvent edge %s", name)
}

// PurchaseOrderMutation represents an operation that mutates the PurchaseOrder nodes in the graph.
type PurchaseOrderMutation struct {
	config
	op              Op
	typ             string
	id              *string
	owner_subject   *string
	idempotency_key *string
	status          *string
	total_cents     *int64
	addtotal_cents  *int64
	created_at      *time.Time
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*PurchaseOrder, error)
	predicates      []predicate.PurchaseOrder
}

var _ ent.Mutation = (*PurchaseOrderMutation)(nil)

// purchaseorderOption allows management of the mutation configuration using functional options.
type purchaseorderOption func(*PurchaseOrderMutation)

// newPurchaseOrderMutation creates new mutation for the PurchaseOrder entity.
func newPurchaseOrderMutation(c config, op Op, opts ...purchaseorderOption) *PurchaseOrderMutation {
	m := &PurchaseOrderMutation{
		config:        c,
		op:            op,
		typ:           TypePurchaseOrder,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPurchaseOrderID sets the ID field of the mutation.
func withPurchaseOrderID(id string) purchaseorderOption {
	return func(m *PurchaseOrderMutation) {
		var (
			err   error
			once  sync.Once
			value *PurchaseOrder
		)
		m.oldValue = func(ctx context.Context) (*PurchaseOrder, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PurchaseOrder.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPurchaseOrder sets the old PurchaseOrder of the mutation.
func withPurchaseOrder(node *PurchaseOrder) purchaseorderOption {
	return func(m *PurchaseOrderMutation) {
		m.oldValue = func(context.Context) (*PurchaseOrder, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PurchaseOrderMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PurchaseOrderMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of PurchaseOrder entities.
func (m *PurchaseOrderMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PurchaseOrderMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PurchaseOrderMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PurchaseOrder.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetOwnerSubject sets the "owner_subject" field.
func (m *PurchaseOrderMutation) SetOwnerSubject(s string) {
	m.owner_subject = &s
}

// OwnerSubject returns the value of the "owner_subject" field in the mutation.
func (m *PurchaseOrderMutation) OwnerSubject() (r string, exists bool) {
	v := m.owner_subject
	if v == nil {
		return
	}
	return *v, true
}

// OldOwnerSubject returns the old "owner_subject" field's value of the PurchaseOrder entity.
// If the PurchaseOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PurchaseOrderMutation) OldOwnerSubject(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOwnerSubject is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOwnerSubject requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOwnerSubject: %w", err)
	}
	return oldValue.OwnerSubject, nil
}

// ResetOwnerSubject resets all changes to the "owner_subject" field.
func (m *PurchaseOrderMutation) ResetOwnerSubject() {
	m.owner_subject = nil
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (m *PurchaseOrderMutation) SetIdempotencyKey(s string) {
	m.idempotency_key = &s
}

// IdempotencyKey returns the value of the "idempotency_key" field in the mutation.
func (m *PurchaseOrderMutation) IdempotencyKey() (r string, exists bool) {
	v := m.idempotency_key
	if v == nil {
		return
	}
	return *v, true
}

// OldIdempotencyKey returns the old "idempotency_key" field's value of the PurchaseOrder entity.
// If the PurchaseOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PurchaseOrderMutation) OldIdempotencyKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIdempotencyKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIdempotencyKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIdempotencyKey: %w", err)
	}
	return oldValue.IdempotencyKey, nil
}

// ResetIdempotencyKey resets all changes to the "idempotency_key" field.
func (m *PurchaseOrderMutation) ResetIdempotencyKey() {
	m.idempotency_key = nil
}

// SetStatus sets the "status" field.
func (m *PurchaseOrderMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *PurchaseOrderMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the PurchaseOrder entity.
// If the PurchaseOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PurchaseOrderMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *PurchaseOrderMutation) ResetStatus() {
	m.status = nil
}

// SetTotalCents sets the "total_cents" field.
func (m *PurchaseOrderMutation) SetTotalCents(i int64) {
	m.total_cents = &i
	m.addtotal_cents = nil
}

// TotalCents returns the value of the "total_cents" field in the mutation.
func (m *PurchaseOrderMutation) TotalCents() (r int64, exists bool) {
	v := m.total_cents
	if v == nil {
		return
	}
	return *v, true
}

// OldTotalCents returns the old "total_cents" field's value of the PurchaseOrder entity.
// If the PurchaseOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PurchaseOrderMutation) OldTotalCents(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTotalCents is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTotalCents requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTotalCents: %w", err)
	}
	return oldValue.TotalCents, nil
}

// AddTotalCents adds i to the "total_cents" field.
func (m *PurchaseOrderMutation) AddTotalCents(i int64) {
	if m.addtotal_cents != nil {
		*m.addtotal_cents += i
	} else {
		m.addtotal_cents = &i
	}
}

// AddedTotalCents returns the value that was added to the "total_cents" field in this mutation.
func (m *PurchaseOrderMutation) AddedTotalCents() (r int64, exists bool) {
	v := m.addtotal_cents
	if v == nil {
		return
	}
	return *v, true
}

// ResetTotalCents resets all changes to the "total_cents" field.
func (m *PurchaseOrderMutation) ResetTotalCents() {
	m.total_cents = nil
	m.addtotal_cents = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *PurchaseOrderMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *PurchaseOrderMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the PurchaseOrder entity.
// If the PurchaseOrder object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PurchaseOrderMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *PurchaseOrderMutation) ResetCreatedAt() {
	m.created_at = nil
}

// Where appends a list predicates to the PurchaseOrderMutation builder.
func (m *PurchaseOrderMutation) Where(ps ...predicate.PurchaseOrder) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PurchaseOrderMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PurchaseOrderMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PurchaseOrder, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PurchaseOrderMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PurchaseOrderMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PurchaseOrder).
func (m *PurchaseOrderMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PurchaseOrderMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.owner_subject != nil {
		fields = append(fields, purchaseorder.FieldOwnerSubject)
	}
	if m.idempotency_key != nil {
		fields = append(fields, purchaseorder.FieldIdempotencyKey)
	}
	if m.status != nil {
		fields = append(fields, purchaseorder.FieldStatus)
	}
	if m.total_cents != nil {
		fields = append(fields, purchaseorder.FieldTotalCents)
	}
	if m.created_at != nil {
		fields = append(fields, purchaseorder.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PurchaseOrderMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case purchaseorder.FieldOwnerSubject:
		return m.OwnerSubject()
	case purchaseorder.FieldIdempotencyKey:
		return m.IdempotencyKey()
	case purchaseorder.FieldStatus:
		return m.Status()
	case purchaseorder.FieldTotalCents:
		return m.TotalCents()
	case purchaseorder.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PurchaseOrderMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case purchaseorder.FieldOwnerSubject:
		return m.OldOwnerSubject(ctx)
	case purchaseorder.FieldIdempotencyKey:
		return m.OldIdempotencyKey(ctx)
	case purchaseorder.FieldStatus:
		return m.OldStatus(ctx)
	case purchaseorder.FieldTotalCents:
		return m.OldTotalCents(ctx)
	case purchaseorder.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown PurchaseOrder field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PurchaseOrderMutation) SetField(name string, value ent.Value) error {
	switch name {
	case purchaseorder.FieldOwnerSubject:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOwnerSubject(v)
		return nil
	case purchaseorder.FieldIdempotencyKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIdempotencyKey(v)
		return nil
	case purchaseorder.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case purchaseorder.FieldTotalCents:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTotalCents(v)
		return nil
	case purchaseorder.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown PurchaseOrder field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PurchaseOrderMutation) AddedFields() []string {
	var fields []string
	if m.addtotal_cents != nil {
		fields = append(fields, purchaseorder.FieldTotalCents)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PurchaseOrderMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case purchaseorder.FieldTotalCents:
		return m.AddedTotalCents()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PurchaseOrderMutation) AddField(name string, value ent.Value) error {
	switch name {
	case purchaseorder.FieldTotalCents:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTotalCents(v)
		return nil
	}
	return fmt.Errorf("unknown PurchaseOrder numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PurchaseOrderMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PurchaseOrderMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PurchaseOrderMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PurchaseOrder nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PurchaseOrderMutation) ResetField(name string) error {
	switch name {
	case purchaseorder.FieldOwnerSubject:
		m.ResetOwnerSubject()
		return nil
	case purchaseorder.FieldIdempotencyKey:
		m.ResetIdempotencyKey()
		return nil
	case purchaseorder.FieldStatus:
		m.ResetStatus()
		return nil
	case purchaseorder.FieldTotalCents:
		m.ResetTotalCents()
		return nil
	case purchaseorder.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown PurchaseOrder field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PurchaseOrderMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PurchaseOrderMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PurchaseOrderMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PurchaseOrderMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PurchaseOrderMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PurchaseOrderMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PurchaseOrderMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown PurchaseOrder unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PurchaseOrderMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown PurchaseOrder edge %s", name)
}
