// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eagle-go/eagle/app/order/internal/platform/database/ent/orderitem"
	"github.com/eagle-go/eagle/app/order/internal/platform/database/ent/predicate"
)

// OrderItemUpdate is the builder for updating OrderItem entities.
type OrderItemUpdate struct {
	config
	hooks    []Hook
	mutation *OrderItemMutation
}

// Where appends a list predicates to the OrderItemUpdate builder.
func (_u *OrderItemUpdate) Where(ps ...predicate.OrderItem) *OrderItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *OrderItemUpdate) SetOrderID(v string) *OrderItemUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableOrderID(v *string) *OrderItemUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *OrderItemUpdate) SetProductID(v int64) *OrderItemUpdate {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableProductID(v *int64) *OrderItemUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *OrderItemUpdate) AddProductID(v int64) *OrderItemUpdate {
	_u.mutation.AddProductID(v)
	return _u
}

// SetProductSku sets the "product_sku" field.
func (_u *OrderItemUpdate) SetProductSku(v string) *OrderItemUpdate {
	_u.mutation.SetProductSku(v)
	return _u
}

// SetNillableProductSku sets the "product_sku" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableProductSku(v *string) *OrderItemUpdate {
	if v != nil {
		_u.SetProductSku(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *OrderItemUpdate) SetProductName(v string) *OrderItemUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableProductName(v *string) *OrderItemUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetUnitPriceCents sets the "unit_price_cents" field.
func (_u *OrderItemUpdate) SetUnitPriceCents(v int64) *OrderItemUpdate {
	_u.mutation.ResetUnitPriceCents()
	_u.mutation.SetUnitPriceCents(v)
	return _u
}

// SetNillableUnitPriceCents sets the "unit_price_cents" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableUnitPriceCents(v *int64) *OrderItemUpdate {
	if v != nil {
		_u.SetUnitPriceCents(*v)
	}
	return _u
}

// AddUnitPriceCents adds value to the "unit_price_cents" field.
func (_u *OrderItemUpdate) AddUnitPriceCents(v int64) *OrderItemUpdate {
	_u.mutation.AddUnitPriceCents(v)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderItemUpdate) SetQuantity(v int32) *OrderItemUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableQuantity(v *int32) *OrderItemUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderItemUpdate) AddQuantity(v int32) *OrderItemUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetSubtotalCents sets the "subtotal_cents" field.
func (_u *OrderItemUpdate) SetSubtotalCents(v int64) *OrderItemUpdate {
	_u.mutation.ResetSubtotalCents()
	_u.mutation.SetSubtotalCents(v)
	return _u
}

// SetNillableSubtotalCents sets the "subtotal_cents" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableSubtotalCents(v *int64) *OrderItemUpdate {
	if v != nil {
		_u.SetSubtotalCents(*v)
	}
	return _u
}

// AddSubtotalCents adds value to the "subtotal_cents" field.
func (_u *OrderItemUpdate) AddSubtotalCents(v int64) *OrderItemUpdate {
	_u.mutation.AddSubtotalCents(v)
	return _u
}

// Mutation returns the OrderItemMutation object of the builder.
func (_u *OrderItemUpdate) Mutation() *OrderItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderItemUpdate) check() error {
	if v, ok := _u.mutation.OrderID(); ok {
		if err := orderitem.OrderIDValidator(v); err != nil {
			return &ValidationError{Name: "order_id", err: fmt.Errorf(`ent: validator failed for field "OrderItem.order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductID(); ok {
		if err := orderitem.ProductIDValidator(v); err != nil {
			return &ValidationError{Name: "product_id", err: fmt.Errorf(`ent: validator failed for field "OrderItem.product_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductSku(); ok {
		if err := orderitem.ProductSkuValidator(v); err != nil {
			return &ValidationError{Name: "product_sku", err: fmt.Errorf(`ent: validator failed for field "OrderItem.product_sku": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := orderitem.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "OrderItem.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UnitPriceCents(); ok {
		if err := orderitem.UnitPriceCentsValidator(v); err != nil {
			return &ValidationError{Name: "unit_price_cents", err: fmt.Errorf(`ent: validator failed for field "OrderItem.unit_price_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quantity(); ok {
		if err := orderitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderItem.quantity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubtotalCents(); ok {
		if err := orderitem.SubtotalCentsValidator(v); err != nil {
			return &ValidationError{Name: "subtotal_cents", err: fmt.Errorf(`ent: validator failed for field "OrderItem.subtotal_cents": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderitem.Table, orderitem.Columns, sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(orderitem.FieldOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(orderitem.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(orderitem.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductSku(); ok {
		_spec.SetField(orderitem.FieldProductSku, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(orderitem.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnitPriceCents(); ok {
		_spec.SetField(orderitem.FieldUnitPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnitPriceCents(); ok {
		_spec.AddField(orderitem.FieldUnitPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(orderitem.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(orderitem.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.SubtotalCents(); ok {
		_spec.SetField(orderitem.FieldSubtotalCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubtotalCents(); ok {
		_spec.AddField(orderitem.FieldSubtotalCents, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderItemUpdateOne is the builder for updating a single OrderItem entity.
type OrderItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderItemMutation
}

// SetOrderID sets the "order_id" field.
func (_u *OrderItemUpdateOne) SetOrderID(v string) *OrderItemUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableOrderID(v *string) *OrderItemUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *OrderItemUpdateOne) SetProductID(v int64) *OrderItemUpdateOne {
	_u.mutation.ResetProductID()
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableProductID(v *int64) *OrderItemUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// AddProductID adds value to the "product_id" field.
func (_u *OrderItemUpdateOne) AddProductID(v int64) *OrderItemUpdateOne {
	_u.mutation.AddProductID(v)
	return _u
}

// SetProductSku sets the "product_sku" field.
func (_u *OrderItemUpdateOne) SetProductSku(v string) *OrderItemUpdateOne {
	_u.mutation.SetProductSku(v)
	return _u
}

// SetNillableProductSku sets the "product_sku" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableProductSku(v *string) *OrderItemUpdateOne {
	if v != nil {
		_u.SetProductSku(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *OrderItemUpdateOne) SetProductName(v string) *OrderItemUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableProductName(v *string) *OrderItemUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetUnitPriceCents sets the "unit_price_cents" field.
func (_u *OrderItemUpdateOne) SetUnitPriceCents(v int64) *OrderItemUpdateOne {
	_u.mutation.ResetUnitPriceCents()
	_u.mutation.SetUnitPriceCents(v)
	return _u
}

// SetNillableUnitPriceCents sets the "unit_price_cents" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableUnitPriceCents(v *int64) *OrderItemUpdateOne {
	if v != nil {
		_u.SetUnitPriceCents(*v)
	}
	return _u
}

// AddUnitPriceCents adds value to the "unit_price_cents" field.
func (_u *OrderItemUpdateOne) AddUnitPriceCents(v int64) *OrderItemUpdateOne {
	_u.mutation.AddUnitPriceCents(v)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderItemUpdateOne) SetQuantity(v int32) *OrderItemUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableQuantity(v *int32) *OrderItemUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderItemUpdateOne) AddQuantity(v int32) *OrderItemUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetSubtotalCents sets the "subtotal_cents" field.
func (_u *OrderItemUpdateOne) SetSubtotalCents(v int64) *OrderItemUpdateOne {
	_u.mutation.ResetSubtotalCents()
	_u.mutation.SetSubtotalCents(v)
	return _u
}

// SetNillableSubtotalCents sets the "subtotal_cents" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableSubtotalCents(v *int64) *OrderItemUpdateOne {
	if v != nil {
		_u.SetSubtotalCents(*v)
	}
	return _u
}

// AddSubtotalCents adds value to the "subtotal_cents" field.
func (_u *OrderItemUpdateOne) AddSubtotalCents(v int64) *OrderItemUpdateOne {
	_u.mutation.AddSubtotalCents(v)
	return _u
}

// Mutation returns the OrderItemMutation object of the builder.
func (_u *OrderItemUpdateOne) Mutation() *OrderItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrderItemUpdate builder.
func (_u *OrderItemUpdateOne) Where(ps ...predicate.OrderItem) *OrderItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderItemUpdateOne) Select(field string, fields ...string) *OrderItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderItem entity.
func (_u *OrderItemUpdateOne) Save(ctx context.Context) (*OrderItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderItemUpdateOne) SaveX(ctx context.Context) *OrderItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderItemUpdateOne) check() error {
	if v, ok := _u.mutation.OrderID(); ok {
		if err := orderitem.OrderIDValidator(v); err != nil {
			return &ValidationError{Name: "order_id", err: fmt.Errorf(`ent: validator failed for field "OrderItem.order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductID(); ok {
		if err := orderitem.ProductIDValidator(v); err != nil {
			return &ValidationError{Name: "product_id", err: fmt.Errorf(`ent: validator failed for field "OrderItem.product_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductSku(); ok {
		if err := orderitem.ProductSkuValidator(v); err != nil {
			return &ValidationError{Name: "product_sku", err: fmt.Errorf(`ent: validator failed for field "OrderItem.product_sku": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := orderitem.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "OrderItem.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UnitPriceCents(); ok {
		if err := orderitem.UnitPriceCentsValidator(v); err != nil {
			return &ValidationError{Name: "unit_price_cents", err: fmt.Errorf(`ent: validator failed for field "OrderItem.unit_price_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quantity(); ok {
		if err := orderitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "OrderItem.quantity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubtotalCents(); ok {
		if err := orderitem.SubtotalCentsValidator(v); err != nil {
			return &ValidationError{Name: "subtotal_cents", err: fmt.Errorf(`ent: validator failed for field "OrderItem.subtotal_cents": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderItemUpdateOne) sqlSave(ctx context.Context) (_node *OrderItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderitem.Table, orderitem.Columns, sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderitem.FieldID)
		for _, f := range fields {
			if !orderitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(orderitem.FieldOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(orderitem.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProductID(); ok {
		_spec.AddField(orderitem.FieldProductID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductSku(); ok {
		_spec.SetField(orderitem.FieldProductSku, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(orderitem.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UnitPriceCents(); ok {
		_spec.SetField(orderitem.FieldUnitPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUnitPriceCents(); ok {
		_spec.AddField(orderitem.FieldUnitPriceCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(orderitem.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(orderitem.FieldQuantity, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.SubtotalCents(); ok {
		_spec.SetField(orderitem.FieldSubtotalCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubtotalCents(); ok {
		_spec.AddField(orderitem.FieldSubtotalCents, field.TypeInt64, value)
	}
	_node = &OrderItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
