// Code generated by ent, DO NOT EDIT.

package userrolebinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the userrolebinding type in the database.
	Label = "user_role_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountSubject holds the string denoting the account_subject field in the database.
	FieldAccountSubject = "account_subject"
	// FieldAudience holds the string denoting the audience field in the database.
	FieldAudience = "audience"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the userrolebinding in the database.
	Table = "user_role_binding"
)

// Columns holds all SQL columns for userrolebinding fields.
var Columns = []string{
	FieldID,
	FieldAccountSubject,
	FieldAudience,
	FieldRole,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AccountSubjectValidator is a validator for the "account_subject" field. It is called by the builders before save.
	AccountSubjectValidator func(string) error
	// AudienceValidator is a validator for the "audience" field. It is called by the builders before save.
	AudienceValidator func(string) error
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserRoleBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountSubject orders the results by the account_subject field.
func ByAccountSubject(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountSubject, opts...).ToFunc()
}

// ByAudience orders the results by the audience field.
func ByAudience(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudience, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
