// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/eagle-go/eagle/internal/access/application"
	"github.com/eagle-go/eagle/internal/access/infrastructure"
	"github.com/eagle-go/eagle/internal/access/service"
	infrastructure2 "github.com/eagle-go/eagle/internal/dictionary/infrastructure"
	service2 "github.com/eagle-go/eagle/internal/dictionary/service"
	"github.com/eagle-go/eagle/internal/platform/database"
	"github.com/eagle-go/eagle/pkg/platform/config"
	"github.com/eagle-go/eagle/pkg/platform/runtime"
	"github.com/eagle-go/eagle/pkg/platform/server"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(bc *config.Bootstrap, logger *slog.Logger) (runtime.Components, func(), error) {
	configServer := provideServer(bc)
	auth := provideAuth(bc)
	verifier := server.NewVerifier(auth)
	data := provideData(bc)
	databaseDatabase, cleanup, err := database.Open(data)
	if err != nil {
		return runtime.Components{}, nil, err
	}
	policyStore := infrastructure.NewPolicyStore(databaseDatabase)
	enforcer, err := infrastructure.NewEnforcer(policyStore)
	if err != nil {
		cleanup()
		return runtime.Components{}, nil, err
	}
	authorizer := provideAuthorizer(enforcer)
	v, err := provideMiddlewares(logger, verifier, authorizer, auth)
	if err != nil {
		cleanup()
		return runtime.Components{}, nil, err
	}
	permissionRepo := infrastructure.NewPermissionRepo(databaseDatabase)
	policyRepo := infrastructure.NewPolicyRepo(enforcer, policyStore)
	permissionUsecase := application.NewPermissionUsecase(permissionRepo, policyRepo)
	permissionService := service.NewPermissionService(permissionUsecase)
	roleBindingUsecase := application.NewRoleBindingUsecase(policyRepo, permissionRepo)
	roleBindingService := service.NewRoleBindingService(roleBindingUsecase)
	dictRepo := infrastructure2.NewDictRepo(databaseDatabase)
	dictService := service2.NewDictService(dictRepo)
	httpServer := provideHTTPServer(configServer, v, permissionService, roleBindingService, dictService)
	mainPolicyHealth, cleanup2, err := providePolicyHealth(policyStore, enforcer)
	if err != nil {
		cleanup()
		return runtime.Components{}, nil, err
	}
	mainPolicyReconciler, cleanup3, err := providePolicyReconciler(policyStore, enforcer, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return runtime.Components{}, nil, err
	}
	components := newComponents(httpServer, mainPolicyHealth, mainPolicyReconciler)
	return components, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
