// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OrderItemColumns holds the columns for the "order_item" table.
	OrderItemColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_id", Type: field.TypeString, Size: 36},
		{Name: "product_id", Type: field.TypeInt64},
		{Name: "product_sku", Type: field.TypeString, Size: 64},
		{Name: "product_name", Type: field.TypeString, Size: 128},
		{Name: "unit_price_cents", Type: field.TypeInt64},
		{Name: "quantity", Type: field.TypeInt32},
		{Name: "subtotal_cents", Type: field.TypeInt64},
	}
	// OrderItemTable holds the schema information for the "order_item" table.
	OrderItemTable = &schema.Table{
		Name:       "order_item",
		Columns:    OrderItemColumns,
		PrimaryKey: []*schema.Column{OrderItemColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_order_item_order",
				Unique:  false,
				Columns: []*schema.Column{OrderItemColumns[1]},
			},
			{
				Name:    "orderitem_order_id_product_id",
				Unique:  true,
				Columns: []*schema.Column{OrderItemColumns[1], OrderItemColumns[2]},
			},
		},
	}
	// PurchaseOrderColumns holds the columns for the "purchase_order" table.
	PurchaseOrderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 36},
		{Name: "owner_subject", Type: field.TypeString, Size: 128},
		{Name: "status", Type: field.TypeString, Size: 32},
		{Name: "total_cents", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PurchaseOrderTable holds the schema information for the "purchase_order" table.
	PurchaseOrderTable = &schema.Table{
		Name:       "purchase_order",
		Columns:    PurchaseOrderColumns,
		PrimaryKey: []*schema.Column{PurchaseOrderColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_purchase_order_owner_created",
				Unique:  false,
				Columns: []*schema.Column{PurchaseOrderColumns[1], PurchaseOrderColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OrderItemTable,
		PurchaseOrderTable,
	}
)

func init() {
	OrderItemTable.Annotation = &entsql.Annotation{
		Table: "order_item",
	}
	PurchaseOrderTable.Annotation = &entsql.Annotation{
		Table: "purchase_order",
	}
}
