// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package sqlc

import (
	"context"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO sys_role_permission (role_id, permission_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       int64
	PermissionID int64
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const countChildPermissions = `-- name: CountChildPermissions :one
SELECT count(*) FROM sys_permission WHERE parent_id = $1
`

func (q *Queries) CountChildPermissions(ctx context.Context, parentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countChildPermissions, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO sys_permission (parent_id, name, code, type, path, component, icon, sort, visible, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, parent_id, name, code, type, path, component, icon, sort, visible, status, created_at, updated_at
`

type CreatePermissionParams struct {
	ParentID  int64
	Name      string
	Code      string
	Type      int16
	Path      string
	Component string
	Icon      string
	Sort      int32
	Visible   bool
	Status    int16
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (SysPermission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.ParentID,
		arg.Name,
		arg.Code,
		arg.Type,
		arg.Path,
		arg.Component,
		arg.Icon,
		arg.Sort,
		arg.Visible,
		arg.Status,
	)
	var i SysPermission
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.Path,
		&i.Component,
		&i.Icon,
		&i.Sort,
		&i.Visible,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :execrows
DELETE FROM sys_permission WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePermission, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM sys_role_permission WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID int64) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, parent_id, name, code, type, path, component, icon, sort, visible, status, created_at, updated_at FROM sys_permission WHERE id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id int64) (SysPermission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i SysPermission
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.Path,
		&i.Component,
		&i.Icon,
		&i.Sort,
		&i.Visible,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissionCodesByUserID = `-- name: ListPermissionCodesByUserID :many

SELECT DISTINCT p.code
FROM sys_permission p
JOIN sys_role_permission rp ON rp.permission_id = p.id
JOIN sys_user_role ur       ON ur.role_id = rp.role_id
JOIN sys_role r             ON r.id = ur.role_id
WHERE ur.user_id = $1
  AND p.code <> ''
  AND p.status = 1
  AND r.status = 1
  AND r.deleted_at IS NULL
`

// ── 鉴权热路径 ─────────────────────────────────────────
// authz 中间件的数据来源。结果会进 Redis 缓存，这里只在缓存未命中时走。
func (q *Queries) ListPermissionCodesByUserID(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionIDsByRoleID = `-- name: ListPermissionIDsByRoleID :many

SELECT permission_id FROM sys_role_permission WHERE role_id = $1
`

// ── 角色 ↔ 权限 ────────────────────────────────────────
func (q *Queries) ListPermissionIDsByRoleID(ctx context.Context, roleID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listPermissionIDsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var permission_id int64
		if err := rows.Scan(&permission_id); err != nil {
			return nil, err
		}
		items = append(items, permission_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, parent_id, name, code, type, path, component, icon, sort, visible, status, created_at, updated_at FROM sys_permission
WHERE ($1::smallint IS NULL OR status = $1::smallint)
  AND ($2::smallint IS NULL OR type = $2::smallint)
ORDER BY parent_id, sort, id
`

type ListPermissionsParams struct {
	Status *int16
	Type   *int16
}

// 权限总量有限（百级），一次全量取出在应用层拼树，比递归 CTE 更简单也更快
func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]SysPermission, error) {
	rows, err := q.db.Query(ctx, listPermissions, arg.Status, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysPermission{}
	for rows.Next() {
		var i SysPermission
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.Path,
			&i.Component,
			&i.Icon,
			&i.Sort,
			&i.Visible,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByUserID = `-- name: ListPermissionsByUserID :many
SELECT DISTINCT p.id, p.parent_id, p.name, p.code, p.type, p.path, p.component, p.icon, p.sort, p.visible, p.status, p.created_at, p.updated_at
FROM sys_permission p
JOIN sys_role_permission rp ON rp.permission_id = p.id
JOIN sys_user_role ur       ON ur.role_id = rp.role_id
JOIN sys_role r             ON r.id = ur.role_id
WHERE ur.user_id = $1
  AND p.status = 1
  AND r.status = 1
  AND r.deleted_at IS NULL
ORDER BY p.parent_id, p.sort, p.id
`

// 构建前端菜单树用（含目录/菜单，不只是权限码）
func (q *Queries) ListPermissionsByUserID(ctx context.Context, userID int64) ([]SysPermission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SysPermission{}
	for rows.Next() {
		var i SysPermission
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.Path,
			&i.Component,
			&i.Icon,
			&i.Sort,
			&i.Visible,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsByRoleID = `-- name: ListUserIDsByRoleID :many
SELECT user_id FROM sys_user_role WHERE role_id = $1
`

// 角色权限变更后，用来精准失效这批用户的权限缓存
func (q *Queries) ListUserIDsByRoleID(ctx context.Context, roleID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserIDsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE sys_permission SET
    parent_id  = $1,
    name       = $2,
    code       = $3,
    type       = $4,
    path       = $5,
    component  = $6,
    icon       = $7,
    sort       = $8,
    visible    = $9,
    status     = $10,
    updated_at = now()
WHERE id = $11
RETURNING id, parent_id, name, code, type, path, component, icon, sort, visible, status, created_at, updated_at
`

type UpdatePermissionParams struct {
	ParentID  int64
	Name      string
	Code      string
	Type      int16
	Path      string
	Component string
	Icon      string
	Sort      int32
	Visible   bool
	Status    int16
	ID        int64
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (SysPermission, error) {
	row := q.db.QueryRow(ctx, updatePermission,
		arg.ParentID,
		arg.Name,
		arg.Code,
		arg.Type,
		arg.Path,
		arg.Component,
		arg.Icon,
		arg.Sort,
		arg.Visible,
		arg.Status,
		arg.ID,
	)
	var i SysPermission
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.Path,
		&i.Component,
		&i.Icon,
		&i.Sort,
		&i.Visible,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
