events {}

http {
  client_max_body_size 10m;

  server {
    listen 8000;

    location ^~ /v1/system/files {
      proxy_pass http://admin:8000;
      include /etc/nginx/proxy.conf;
    }
    location ^~ /v1/system/notifications {
      proxy_pass http://admin:8000;
      include /etc/nginx/proxy.conf;
    }
    location ^~ /v1/products {
      proxy_pass http://product:8000;
      include /etc/nginx/proxy.conf;
    }
    location ^~ /v1/orders {
      proxy_pass http://order:8000;
      include /etc/nginx/proxy.conf;
    }
    location / {
      proxy_pass http://admin:8000;
      include /etc/nginx/proxy.conf;
    }
  }
}
