// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eagle/access/v1/error_reason.proto

package accessv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason identifies access-module failures independently of transport status codes.
type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED                ErrorReason = 0
	ErrorReason_ERROR_REASON_PERMISSION_NOT_FOUND       ErrorReason = 20
	ErrorReason_ERROR_REASON_PERMISSION_CODE_DUPLICATED ErrorReason = 21
	ErrorReason_ERROR_REASON_PERMISSION_HAS_CHILDREN    ErrorReason = 22
	ErrorReason_ERROR_REASON_PERMISSION_CYCLE           ErrorReason = 23
	ErrorReason_ERROR_REASON_CONCURRENT_MODIFICATION    ErrorReason = 24
	ErrorReason_ERROR_REASON_INVALID_PERMISSION_CODE    ErrorReason = 25
	ErrorReason_ERROR_REASON_BUTTON_REQUIRES_CODE       ErrorReason = 26
	ErrorReason_ERROR_REASON_INVALID_PERMISSION_TYPE    ErrorReason = 27
	ErrorReason_ERROR_REASON_EMPTY_PERMISSION_NAME      ErrorReason = 28
	ErrorReason_ERROR_REASON_ROLE_NOT_BOUND             ErrorReason = 40
	ErrorReason_ERROR_REASON_UNKNOWN_PERMISSION_CODE    ErrorReason = 41
	ErrorReason_ERROR_REASON_ROLE_INHERITANCE_CYCLE     ErrorReason = 42
	ErrorReason_ERROR_REASON_EMPTY_ROLE                 ErrorReason = 43
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ERROR_REASON_UNSPECIFIED",
		20: "ERROR_REASON_PERMISSION_NOT_FOUND",
		21: "ERROR_REASON_PERMISSION_CODE_DUPLICATED",
		22: "ERROR_REASON_PERMISSION_HAS_CHILDREN",
		23: "ERROR_REASON_PERMISSION_CYCLE",
		24: "ERROR_REASON_CONCURRENT_MODIFICATION",
		25: "ERROR_REASON_INVALID_PERMISSION_CODE",
		26: "ERROR_REASON_BUTTON_REQUIRES_CODE",
		27: "ERROR_REASON_INVALID_PERMISSION_TYPE",
		28: "ERROR_REASON_EMPTY_PERMISSION_NAME",
		40: "ERROR_REASON_ROLE_NOT_BOUND",
		41: "ERROR_REASON_UNKNOWN_PERMISSION_CODE",
		42: "ERROR_REASON_ROLE_INHERITANCE_CYCLE",
		43: "ERROR_REASON_EMPTY_ROLE",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":                0,
		"ERROR_REASON_PERMISSION_NOT_FOUND":       20,
		"ERROR_REASON_PERMISSION_CODE_DUPLICATED": 21,
		"ERROR_REASON_PERMISSION_HAS_CHILDREN":    22,
		"ERROR_REASON_PERMISSION_CYCLE":           23,
		"ERROR_REASON_CONCURRENT_MODIFICATION":    24,
		"ERROR_REASON_INVALID_PERMISSION_CODE":    25,
		"ERROR_REASON_BUTTON_REQUIRES_CODE":       26,
		"ERROR_REASON_INVALID_PERMISSION_TYPE":    27,
		"ERROR_REASON_EMPTY_PERMISSION_NAME":      28,
		"ERROR_REASON_ROLE_NOT_BOUND":             40,
		"ERROR_REASON_UNKNOWN_PERMISSION_CODE":    41,
		"ERROR_REASON_ROLE_INHERITANCE_CYCLE":     42,
		"ERROR_REASON_EMPTY_ROLE":                 43,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_eagle_access_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_eagle_access_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_eagle_access_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_eagle_access_v1_error_reason_proto protoreflect.FileDescriptor

const file_eagle_access_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\"eagle/access/v1/error_reason.proto\x12\x0feagle.access.v1*\xaa\x04\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12%\n" +
	"!ERROR_REASON_PERMISSION_NOT_FOUND\x10\x14\x12+\n" +
	"'ERROR_REASON_PERMISSION_CODE_DUPLICATED\x10\x15\x12(\n" +
	"$ERROR_REASON_PERMISSION_HAS_CHILDREN\x10\x16\x12!\n" +
	"\x1dERROR_REASON_PERMISSION_CYCLE\x10\x17\x12(\n" +
	"$ERROR_REASON_CONCURRENT_MODIFICATION\x10\x18\x12(\n" +
	"$ERROR_REASON_INVALID_PERMISSION_CODE\x10\x19\x12%\n" +
	"!ERROR_REASON_BUTTON_REQUIRES_CODE\x10\x1a\x12(\n" +
	"$ERROR_REASON_INVALID_PERMISSION_TYPE\x10\x1b\x12&\n" +
	"\"ERROR_REASON_EMPTY_PERMISSION_NAME\x10\x1c\x12\x1f\n" +
	"\x1bERROR_REASON_ROLE_NOT_BOUND\x10(\x12(\n" +
	"$ERROR_REASON_UNKNOWN_PERMISSION_CODE\x10)\x12'\n" +
	"#ERROR_REASON_ROLE_INHERITANCE_CYCLE\x10*\x12\x1b\n" +
	"\x17ERROR_REASON_EMPTY_ROLE\x10+B8Z6github.com/eagle-go/eagle/api/eagle/access/v1;accessv1b\x06proto3"

var (
	file_eagle_access_v1_error_reason_proto_rawDescOnce sync.Once
	file_eagle_access_v1_error_reason_proto_rawDescData []byte
)

func file_eagle_access_v1_error_reason_proto_rawDescGZIP() []byte {
	file_eagle_access_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_eagle_access_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eagle_access_v1_error_reason_proto_rawDesc), len(file_eagle_access_v1_error_reason_proto_rawDesc)))
	})
	return file_eagle_access_v1_error_reason_proto_rawDescData
}

var file_eagle_access_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eagle_access_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: eagle.access.v1.ErrorReason
}
var file_eagle_access_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_eagle_access_v1_error_reason_proto_init() }
func file_eagle_access_v1_error_reason_proto_init() {
	if File_eagle_access_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eagle_access_v1_error_reason_proto_rawDesc), len(file_eagle_access_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eagle_access_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_eagle_access_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_eagle_access_v1_error_reason_proto_enumTypes,
	}.Build()
	File_eagle_access_v1_error_reason_proto = out.File
	file_eagle_access_v1_error_reason_proto_goTypes = nil
	file_eagle_access_v1_error_reason_proto_depIdxs = nil
}
