// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: eagle/access/v1/rolebinding.proto

package accessv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationRoleBindingServiceAddRoleInheritance = "/eagle.access.v1.RoleBindingService/AddRoleInheritance"
const OperationRoleBindingServiceDeleteRoleInheritance = "/eagle.access.v1.RoleBindingService/DeleteRoleInheritance"
const OperationRoleBindingServiceGetMyPermissions = "/eagle.access.v1.RoleBindingService/GetMyPermissions"
const OperationRoleBindingServiceGetRolePermissions = "/eagle.access.v1.RoleBindingService/GetRolePermissions"
const OperationRoleBindingServiceListBoundRoles = "/eagle.access.v1.RoleBindingService/ListBoundRoles"
const OperationRoleBindingServiceListRoleInheritances = "/eagle.access.v1.RoleBindingService/ListRoleInheritances"
const OperationRoleBindingServiceSetRolePermissions = "/eagle.access.v1.RoleBindingService/SetRolePermissions"

type RoleBindingServiceHTTPServer interface {
	// AddRoleInheritance AddRoleInheritance 建立 child 到 parent 的继承，child 获得 parent 的权限。
	// 禁止自继承和环；版本校验通过后，重复添加已有关系成功返回且不推进版本。
	AddRoleInheritance(context.Context, *AddRoleInheritanceRequest) (*AddRoleInheritanceResponse, error)
	// DeleteRoleInheritance DeleteRoleInheritance 删除一条继承关系，保留角色的直接授权。
	// 版本校验通过后，关系不存在也成功返回且不推进版本。
	DeleteRoleInheritance(context.Context, *DeleteRoleInheritanceRequest) (*DeleteRoleInheritanceResponse, error)
	// GetMyPermissions GetMyPermissions 按当前主体的 Eagle 角色汇总权限，展开继承并去重，保留权限通配码。
	// 结果来自本实例已加载的策略，供前端控制按钮显隐。
	GetMyPermissions(context.Context, *GetMyPermissionsRequest) (*GetMyPermissionsResponse, error)
	// GetRolePermissions GetRolePermissions 查询角色的直接权限，不展开继承；没有直接授权时返回角色未绑定错误。
	GetRolePermissions(context.Context, *GetRolePermissionsRequest) (*GetRolePermissionsResponse, error)
	// ListBoundRoles ListBoundRoles 按角色键升序列出当前有直接授权的角色及一致的全局策略版本。
	// 没有直接授权、仅通过继承获得权限的角色不在列表中。
	ListBoundRoles(context.Context, *ListBoundRolesRequest) (*ListBoundRolesResponse, error)
	// ListRoleInheritances ListRoleInheritances 按 child、parent 升序列出继承关系及一致的全局策略版本。
	ListRoleInheritances(context.Context, *ListRoleInheritancesRequest) (*ListRoleInheritancesResponse, error)
	// SetRolePermissions SetRolePermissions 全量覆盖角色的直接权限，自动去重；具体权限码必须已登记且启用。
	// 空集合清除直接授权，继承关系保留；每次成功写入都会推进全局策略版本。
	SetRolePermissions(context.Context, *SetRolePermissionsRequest) (*SetRolePermissionsResponse, error)
}

func RegisterRoleBindingServiceHTTPServer(s *http.Server, srv RoleBindingServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/system/role-bindings", _RoleBindingService_ListBoundRoles0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/system/role-bindings/{role}", _RoleBindingService_GetRolePermissions0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/system/role-bindings/{role}", _RoleBindingService_SetRolePermissions0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/system/role-bindings/inheritance", _RoleBindingService_AddRoleInheritance0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/system/role-inheritances", _RoleBindingService_ListRoleInheritances0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/system/role-inheritances/{child}/{parent}", _RoleBindingService_DeleteRoleInheritance0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/system/role-bindings/me/permissions", _RoleBindingService_GetMyPermissions0_HTTP_Handler(srv))
}

func _RoleBindingService_ListBoundRoles0_HTTP_Handler(srv RoleBindingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBoundRolesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoleBindingServiceListBoundRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBoundRoles(ctx, req.(*ListBoundRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBoundRolesResponse)
		return ctx.Result(200, reply)
	}
}

func _RoleBindingService_GetRolePermissions0_HTTP_Handler(srv RoleBindingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRolePermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoleBindingServiceGetRolePermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRolePermissions(ctx, req.(*GetRolePermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRolePermissionsResponse)
		return ctx.Result(200, reply)
	}
}

func _RoleBindingService_SetRolePermissions0_HTTP_Handler(srv RoleBindingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetRolePermissionsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoleBindingServiceSetRolePermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetRolePermissions(ctx, req.(*SetRolePermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetRolePermissionsResponse)
		return ctx.Result(200, reply)
	}
}

func _RoleBindingService_AddRoleInheritance0_HTTP_Handler(srv RoleBindingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddRoleInheritanceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoleBindingServiceAddRoleInheritance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddRoleInheritance(ctx, req.(*AddRoleInheritanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddRoleInheritanceResponse)
		return ctx.Result(200, reply)
	}
}

func _RoleBindingService_ListRoleInheritances0_HTTP_Handler(srv RoleBindingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRoleInheritancesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoleBindingServiceListRoleInheritances)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoleInheritances(ctx, req.(*ListRoleInheritancesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoleInheritancesResponse)
		return ctx.Result(200, reply)
	}
}

func _RoleBindingService_DeleteRoleInheritance0_HTTP_Handler(srv RoleBindingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRoleInheritanceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoleBindingServiceDeleteRoleInheritance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRoleInheritance(ctx, req.(*DeleteRoleInheritanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteRoleInheritanceResponse)
		return ctx.Result(200, reply)
	}
}

func _RoleBindingService_GetMyPermissions0_HTTP_Handler(srv RoleBindingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMyPermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRoleBindingServiceGetMyPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMyPermissions(ctx, req.(*GetMyPermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMyPermissionsResponse)
		return ctx.Result(200, reply)
	}
}

type RoleBindingServiceHTTPClient interface {
	// AddRoleInheritance AddRoleInheritance 建立 child 到 parent 的继承，child 获得 parent 的权限。
	// 禁止自继承和环；版本校验通过后，重复添加已有关系成功返回且不推进版本。
	AddRoleInheritance(ctx context.Context, req *AddRoleInheritanceRequest, opts ...http.CallOption) (rsp *AddRoleInheritanceResponse, err error)
	// DeleteRoleInheritance DeleteRoleInheritance 删除一条继承关系，保留角色的直接授权。
	// 版本校验通过后，关系不存在也成功返回且不推进版本。
	DeleteRoleInheritance(ctx context.Context, req *DeleteRoleInheritanceRequest, opts ...http.CallOption) (rsp *DeleteRoleInheritanceResponse, err error)
	// GetMyPermissions GetMyPermissions 按当前主体的 Eagle 角色汇总权限，展开继承并去重，保留权限通配码。
	// 结果来自本实例已加载的策略，供前端控制按钮显隐。
	GetMyPermissions(ctx context.Context, req *GetMyPermissionsRequest, opts ...http.CallOption) (rsp *GetMyPermissionsResponse, err error)
	// GetRolePermissions GetRolePermissions 查询角色的直接权限，不展开继承；没有直接授权时返回角色未绑定错误。
	GetRolePermissions(ctx context.Context, req *GetRolePermissionsRequest, opts ...http.CallOption) (rsp *GetRolePermissionsResponse, err error)
	// ListBoundRoles ListBoundRoles 按角色键升序列出当前有直接授权的角色及一致的全局策略版本。
	// 没有直接授权、仅通过继承获得权限的角色不在列表中。
	ListBoundRoles(ctx context.Context, req *ListBoundRolesRequest, opts ...http.CallOption) (rsp *ListBoundRolesResponse, err error)
	// ListRoleInheritances ListRoleInheritances 按 child、parent 升序列出继承关系及一致的全局策略版本。
	ListRoleInheritances(ctx context.Context, req *ListRoleInheritancesRequest, opts ...http.CallOption) (rsp *ListRoleInheritancesResponse, err error)
	// SetRolePermissions SetRolePermissions 全量覆盖角色的直接权限，自动去重；具体权限码必须已登记且启用。
	// 空集合清除直接授权，继承关系保留；每次成功写入都会推进全局策略版本。
	SetRolePermissions(ctx context.Context, req *SetRolePermissionsRequest, opts ...http.CallOption) (rsp *SetRolePermissionsResponse, err error)
}

type RoleBindingServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRoleBindingServiceHTTPClient(client *http.Client) RoleBindingServiceHTTPClient {
	return &RoleBindingServiceHTTPClientImpl{client}
}

// AddRoleInheritance AddRoleInheritance 建立 child 到 parent 的继承，child 获得 parent 的权限。
// 禁止自继承和环；版本校验通过后，重复添加已有关系成功返回且不推进版本。
func (c *RoleBindingServiceHTTPClientImpl) AddRoleInheritance(ctx context.Context, in *AddRoleInheritanceRequest, opts ...http.CallOption) (*AddRoleInheritanceResponse, error) {
	var out AddRoleInheritanceResponse
	pattern := "/v1/system/role-bindings/inheritance"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRoleBindingServiceAddRoleInheritance),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteRoleInheritance DeleteRoleInheritance 删除一条继承关系，保留角色的直接授权。
// 版本校验通过后，关系不存在也成功返回且不推进版本。
func (c *RoleBindingServiceHTTPClientImpl) DeleteRoleInheritance(ctx context.Context, in *DeleteRoleInheritanceRequest, opts ...http.CallOption) (*DeleteRoleInheritanceResponse, error) {
	var out DeleteRoleInheritanceResponse
	pattern := "/v1/system/role-inheritances/{child}/{parent}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRoleBindingServiceDeleteRoleInheritance),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMyPermissions GetMyPermissions 按当前主体的 Eagle 角色汇总权限，展开继承并去重，保留权限通配码。
// 结果来自本实例已加载的策略，供前端控制按钮显隐。
func (c *RoleBindingServiceHTTPClientImpl) GetMyPermissions(ctx context.Context, in *GetMyPermissionsRequest, opts ...http.CallOption) (*GetMyPermissionsResponse, error) {
	var out GetMyPermissionsResponse
	pattern := "/v1/system/role-bindings/me/permissions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRoleBindingServiceGetMyPermissions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRolePermissions GetRolePermissions 查询角色的直接权限，不展开继承；没有直接授权时返回角色未绑定错误。
func (c *RoleBindingServiceHTTPClientImpl) GetRolePermissions(ctx context.Context, in *GetRolePermissionsRequest, opts ...http.CallOption) (*GetRolePermissionsResponse, error) {
	var out GetRolePermissionsResponse
	pattern := "/v1/system/role-bindings/{role}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRoleBindingServiceGetRolePermissions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListBoundRoles ListBoundRoles 按角色键升序列出当前有直接授权的角色及一致的全局策略版本。
// 没有直接授权、仅通过继承获得权限的角色不在列表中。
func (c *RoleBindingServiceHTTPClientImpl) ListBoundRoles(ctx context.Context, in *ListBoundRolesRequest, opts ...http.CallOption) (*ListBoundRolesResponse, error) {
	var out ListBoundRolesResponse
	pattern := "/v1/system/role-bindings"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRoleBindingServiceListBoundRoles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRoleInheritances ListRoleInheritances 按 child、parent 升序列出继承关系及一致的全局策略版本。
func (c *RoleBindingServiceHTTPClientImpl) ListRoleInheritances(ctx context.Context, in *ListRoleInheritancesRequest, opts ...http.CallOption) (*ListRoleInheritancesResponse, error) {
	var out ListRoleInheritancesResponse
	pattern := "/v1/system/role-inheritances"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRoleBindingServiceListRoleInheritances),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetRolePermissions SetRolePermissions 全量覆盖角色的直接权限，自动去重；具体权限码必须已登记且启用。
// 空集合清除直接授权，继承关系保留；每次成功写入都会推进全局策略版本。
func (c *RoleBindingServiceHTTPClientImpl) SetRolePermissions(ctx context.Context, in *SetRolePermissionsRequest, opts ...http.CallOption) (*SetRolePermissionsResponse, error) {
	var out SetRolePermissionsResponse
	pattern := "/v1/system/role-bindings/{role}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRoleBindingServiceSetRolePermissions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
