// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: eagle/auth/v1/auth.proto

package authv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAuthServiceGetJSONWebKeySet = "/eagle.auth.v1.AuthService/GetJSONWebKeySet"
const OperationAuthServiceLogout = "/eagle.auth.v1.AuthService/Logout"
const OperationAuthServiceRefreshToken = "/eagle.auth.v1.AuthService/RefreshToken"
const OperationAuthServiceSocialLogin = "/eagle.auth.v1.AuthService/SocialLogin"

type AuthServiceHTTPServer interface {
	// GetJSONWebKeySet GetJSONWebKeySet 公开 access token 验签公钥，供网关和资源服务缓存。
	GetJSONWebKeySet(context.Context, *GetJSONWebKeySetRequest) (*GetJSONWebKeySetResponse, error)
	// Logout Logout 使用当前刷新凭证撤销对应会话；无效或已撤销的凭证返回错误。
	// 已签发的 access token 在自身有效期内仍可通过资源服务验签。
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// RefreshToken RefreshToken 轮换刷新凭证并签发新的 access token，成功后旧刷新凭证不可再次使用。
	// 签发失败时回滚轮换；无效、过期或已撤销的刷新凭证不能刷新，停用账号不能刷新。
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE 预生产既有响应契约，保持客户端 wire/source 兼容。
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME 预生产既有响应契约，保持客户端 wire/source 兼容。
	RefreshToken(context.Context, *RefreshTokenRequest) (*TokenResponse, error)
	// SocialLogin SocialLogin 校验 Google/Apple ID Token 和 nonce，为对应 Eagle 账号创建会话并返回令牌。
	// 同一第三方身份复用已有账号；每次成功登录创建独立会话，停用账号不能登录。
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE 预生产既有响应契约，保持客户端 wire/source 兼容。
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME 预生产既有响应契约，保持客户端 wire/source 兼容。
	SocialLogin(context.Context, *SocialLoginRequest) (*TokenResponse, error)
}

func RegisterAuthServiceHTTPServer(s *http.Server, srv AuthServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/.well-known/jwks.json", _AuthService_GetJSONWebKeySet0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/auth/social/login", _AuthService_SocialLogin0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/auth/token/refresh", _AuthService_RefreshToken0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/auth/logout", _AuthService_Logout0_HTTP_Handler(srv))
}

func _AuthService_GetJSONWebKeySet0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetJSONWebKeySetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceGetJSONWebKeySet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetJSONWebKeySet(ctx, req.(*GetJSONWebKeySetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetJSONWebKeySetResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthService_SocialLogin0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SocialLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceSocialLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SocialLogin(ctx, req.(*SocialLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TokenResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthService_RefreshToken0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefreshTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceRefreshToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RefreshToken(ctx, req.(*RefreshTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TokenResponse)
		return ctx.Result(200, reply)
	}
}

func _AuthService_Logout0_HTTP_Handler(srv AuthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAuthServiceLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutResponse)
		return ctx.Result(200, reply)
	}
}

type AuthServiceHTTPClient interface {
	// GetJSONWebKeySet GetJSONWebKeySet 公开 access token 验签公钥，供网关和资源服务缓存。
	GetJSONWebKeySet(ctx context.Context, req *GetJSONWebKeySetRequest, opts ...http.CallOption) (rsp *GetJSONWebKeySetResponse, err error)
	// Logout Logout 使用当前刷新凭证撤销对应会话；无效或已撤销的凭证返回错误。
	// 已签发的 access token 在自身有效期内仍可通过资源服务验签。
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *LogoutResponse, err error)
	// RefreshToken RefreshToken 轮换刷新凭证并签发新的 access token，成功后旧刷新凭证不可再次使用。
	// 签发失败时回滚轮换；无效、过期或已撤销的刷新凭证不能刷新，停用账号不能刷新。
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE 预生产既有响应契约，保持客户端 wire/source 兼容。
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME 预生产既有响应契约，保持客户端 wire/source 兼容。
	RefreshToken(ctx context.Context, req *RefreshTokenRequest, opts ...http.CallOption) (rsp *TokenResponse, err error)
	// SocialLogin SocialLogin 校验 Google/Apple ID Token 和 nonce，为对应 Eagle 账号创建会话并返回令牌。
	// 同一第三方身份复用已有账号；每次成功登录创建独立会话，停用账号不能登录。
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE 预生产既有响应契约，保持客户端 wire/source 兼容。
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME 预生产既有响应契约，保持客户端 wire/source 兼容。
	SocialLogin(ctx context.Context, req *SocialLoginRequest, opts ...http.CallOption) (rsp *TokenResponse, err error)
}

type AuthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAuthServiceHTTPClient(client *http.Client) AuthServiceHTTPClient {
	return &AuthServiceHTTPClientImpl{client}
}

// GetJSONWebKeySet GetJSONWebKeySet 公开 access token 验签公钥，供网关和资源服务缓存。
func (c *AuthServiceHTTPClientImpl) GetJSONWebKeySet(ctx context.Context, in *GetJSONWebKeySetRequest, opts ...http.CallOption) (*GetJSONWebKeySetResponse, error) {
	var out GetJSONWebKeySetResponse
	pattern := "/.well-known/jwks.json"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAuthServiceGetJSONWebKeySet),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Logout Logout 使用当前刷新凭证撤销对应会话；无效或已撤销的凭证返回错误。
// 已签发的 access token 在自身有效期内仍可通过资源服务验签。
func (c *AuthServiceHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*LogoutResponse, error) {
	var out LogoutResponse
	pattern := "/v1/auth/logout"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAuthServiceLogout),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RefreshToken RefreshToken 轮换刷新凭证并签发新的 access token，成功后旧刷新凭证不可再次使用。
// 签发失败时回滚轮换；无效、过期或已撤销的刷新凭证不能刷新，停用账号不能刷新。
// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE 预生产既有响应契约，保持客户端 wire/source 兼容。
// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME 预生产既有响应契约，保持客户端 wire/source 兼容。
func (c *AuthServiceHTTPClientImpl) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...http.CallOption) (*TokenResponse, error) {
	var out TokenResponse
	pattern := "/v1/auth/token/refresh"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAuthServiceRefreshToken),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SocialLogin SocialLogin 校验 Google/Apple ID Token 和 nonce，为对应 Eagle 账号创建会话并返回令牌。
// 同一第三方身份复用已有账号；每次成功登录创建独立会话，停用账号不能登录。
// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE 预生产既有响应契约，保持客户端 wire/source 兼容。
// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME 预生产既有响应契约，保持客户端 wire/source 兼容。
func (c *AuthServiceHTTPClientImpl) SocialLogin(ctx context.Context, in *SocialLoginRequest, opts ...http.CallOption) (*TokenResponse, error) {
	var out TokenResponse
	pattern := "/v1/auth/social/login"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAuthServiceSocialLogin),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
