// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CasbinRuleColumns holds the columns for the "casbin_rule" table.
	CasbinRuleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "ptype", Type: field.TypeString, Size: 8},
		{Name: "v0", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "v1", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "v2", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "v3", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "v4", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "v5", Type: field.TypeString, Size: 128, Default: ""},
	}
	// CasbinRuleTable holds the schema information for the "casbin_rule" table.
	CasbinRuleTable = &schema.Table{
		Name:       "casbin_rule",
		Columns:    CasbinRuleColumns,
		PrimaryKey: []*schema.Column{CasbinRuleColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "casbinrule_ptype_v0_v1_v2_v3_v4_v5",
				Unique:  true,
				Columns: []*schema.Column{CasbinRuleColumns[1], CasbinRuleColumns[2], CasbinRuleColumns[3], CasbinRuleColumns[4], CasbinRuleColumns[5], CasbinRuleColumns[6], CasbinRuleColumns[7]},
			},
			{
				Name:    "casbinrule_ptype_v0",
				Unique:  false,
				Columns: []*schema.Column{CasbinRuleColumns[1], CasbinRuleColumns[2]},
			},
		},
	}
	// SysDictDataColumns holds the columns for the "sys_dict_data" table.
	SysDictDataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "dict_type", Type: field.TypeString, Size: 64},
		{Name: "label", Type: field.TypeString, Size: 128},
		{Name: "value", Type: field.TypeString, Size: 128},
		{Name: "sort", Type: field.TypeInt32, Default: 0},
		{Name: "css_class", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeInt32, Default: 1},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SysDictDataTable holds the schema information for the "sys_dict_data" table.
	SysDictDataTable = &schema.Table{
		Name:       "sys_dict_data",
		Columns:    SysDictDataColumns,
		PrimaryKey: []*schema.Column{SysDictDataColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "dictdata_dict_type_value",
				Unique:  true,
				Columns: []*schema.Column{SysDictDataColumns[1], SysDictDataColumns[3]},
			},
			{
				Name:    "dictdata_dict_type_sort",
				Unique:  false,
				Columns: []*schema.Column{SysDictDataColumns[1], SysDictDataColumns[4]},
			},
		},
	}
	// SysDictTypeColumns holds the columns for the "sys_dict_type" table.
	SysDictTypeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 64},
		{Name: "type", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "status", Type: field.TypeInt32, Default: 1},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SysDictTypeTable holds the schema information for the "sys_dict_type" table.
	SysDictTypeTable = &schema.Table{
		Name:       "sys_dict_type",
		Columns:    SysDictTypeColumns,
		PrimaryKey: []*schema.Column{SysDictTypeColumns[0]},
	}
	// SysPermissionColumns holds the columns for the "sys_permission" table.
	SysPermissionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "parent_id", Type: field.TypeInt64, Default: 0},
		{Name: "name", Type: field.TypeString, Size: 64},
		{Name: "code", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "type", Type: field.TypeInt32},
		{Name: "path", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "component", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "icon", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "sort", Type: field.TypeInt32, Default: 0},
		{Name: "visible", Type: field.TypeBool, Default: true},
		{Name: "status", Type: field.TypeInt32, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SysPermissionTable holds the schema information for the "sys_permission" table.
	SysPermissionTable = &schema.Table{
		Name:       "sys_permission",
		Columns:    SysPermissionColumns,
		PrimaryKey: []*schema.Column{SysPermissionColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permission_code",
				Unique:  true,
				Columns: []*schema.Column{SysPermissionColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					Where: "code <> ''",
				},
			},
			{
				Name:    "permission_parent_id",
				Unique:  false,
				Columns: []*schema.Column{SysPermissionColumns[1]},
			},
		},
	}
	// SysUserProfileColumns holds the columns for the "sys_user_profile" table.
	SysUserProfileColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "subject", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "dept_id", Type: field.TypeInt64, Default: 0},
		{Name: "position", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "remark", Type: field.TypeString, Default: ""},
		{Name: "last_seen_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SysUserProfileTable holds the schema information for the "sys_user_profile" table.
	SysUserProfileTable = &schema.Table{
		Name:       "sys_user_profile",
		Columns:    SysUserProfileColumns,
		PrimaryKey: []*schema.Column{SysUserProfileColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userprofile_dept_id",
				Unique:  false,
				Columns: []*schema.Column{SysUserProfileColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CasbinRuleTable,
		SysDictDataTable,
		SysDictTypeTable,
		SysPermissionTable,
		SysUserProfileTable,
	}
)

func init() {
	CasbinRuleTable.Annotation = &entsql.Annotation{
		Table: "casbin_rule",
	}
	SysDictDataTable.Annotation = &entsql.Annotation{
		Table: "sys_dict_data",
	}
	SysDictTypeTable.Annotation = &entsql.Annotation{
		Table: "sys_dict_type",
	}
	SysPermissionTable.Annotation = &entsql.Annotation{
		Table: "sys_permission",
	}
	SysUserProfileTable.Annotation = &entsql.Annotation{
		Table: "sys_user_profile",
	}
}
