// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eagle-go/eagle/ent/permissiondefinition"
	"github.com/eagle-go/eagle/ent/predicate"
)

// PermissionDefinitionDelete is the builder for deleting a PermissionDefinition entity.
type PermissionDefinitionDelete struct {
	config
	hooks    []Hook
	mutation *PermissionDefinitionMutation
}

// Where appends a list predicates to the PermissionDefinitionDelete builder.
func (_d *PermissionDefinitionDelete) Where(ps ...predicate.PermissionDefinition) *PermissionDefinitionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PermissionDefinitionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PermissionDefinitionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PermissionDefinitionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(permissiondefinition.Table, sqlgraph.NewFieldSpec(permissiondefinition.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PermissionDefinitionDeleteOne is the builder for deleting a single PermissionDefinition entity.
type PermissionDefinitionDeleteOne struct {
	_d *PermissionDefinitionDelete
}

// Where appends a list predicates to the PermissionDefinitionDelete builder.
func (_d *PermissionDefinitionDeleteOne) Where(ps ...predicate.PermissionDefinition) *PermissionDefinitionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PermissionDefinitionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{permissiondefinition.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PermissionDefinitionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
