// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/eagle-go/eagle/ent/policyaudit"
)

// PolicyAudit is the model entity for the PolicyAudit schema.
type PolicyAudit struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// PolicyVersion holds the value of the "policy_version" field.
	PolicyVersion int64 `json:"policy_version,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// Target holds the value of the "target" field.
	Target string `json:"target,omitempty"`
	// ActorSubject holds the value of the "actor_subject" field.
	ActorSubject string `json:"actor_subject,omitempty"`
	// ActorClientID holds the value of the "actor_client_id" field.
	ActorClientID string `json:"actor_client_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// TraceID holds the value of the "trace_id" field.
	TraceID string `json:"trace_id,omitempty"`
	// Before holds the value of the "before" field.
	Before []string `json:"before,omitempty"`
	// After holds the value of the "after" field.
	After []string `json:"after,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PolicyAudit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case policyaudit.FieldBefore, policyaudit.FieldAfter:
			values[i] = new([]byte)
		case policyaudit.FieldID, policyaudit.FieldPolicyVersion:
			values[i] = new(sql.NullInt64)
		case policyaudit.FieldAction, policyaudit.FieldTarget, policyaudit.FieldActorSubject, policyaudit.FieldActorClientID, policyaudit.FieldRequestID, policyaudit.FieldTraceID:
			values[i] = new(sql.NullString)
		case policyaudit.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PolicyAudit fields.
func (_m *PolicyAudit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case policyaudit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case policyaudit.FieldPolicyVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field policy_version", values[i])
			} else if value.Valid {
				_m.PolicyVersion = value.Int64
			}
		case policyaudit.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case policyaudit.FieldTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.String
			}
		case policyaudit.FieldActorSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_subject", values[i])
			} else if value.Valid {
				_m.ActorSubject = value.String
			}
		case policyaudit.FieldActorClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_client_id", values[i])
			} else if value.Valid {
				_m.ActorClientID = value.String
			}
		case policyaudit.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case policyaudit.FieldTraceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trace_id", values[i])
			} else if value.Valid {
				_m.TraceID = value.String
			}
		case policyaudit.FieldBefore:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field before", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Before); err != nil {
					return fmt.Errorf("unmarshal field before: %w", err)
				}
			}
		case policyaudit.FieldAfter:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field after", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.After); err != nil {
					return fmt.Errorf("unmarshal field after: %w", err)
				}
			}
		case policyaudit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PolicyAudit.
// This includes values selected through modifiers, order, etc.
func (_m *PolicyAudit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PolicyAudit.
// Note that you need to call PolicyAudit.Unwrap() before calling this method if this PolicyAudit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PolicyAudit) Update() *PolicyAuditUpdateOne {
	return NewPolicyAuditClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PolicyAudit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PolicyAudit) Unwrap() *PolicyAudit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PolicyAudit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PolicyAudit) String() string {
	var builder strings.Builder
	builder.WriteString("PolicyAudit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("policy_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.PolicyVersion))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("target=")
	builder.WriteString(_m.Target)
	builder.WriteString(", ")
	builder.WriteString("actor_subject=")
	builder.WriteString(_m.ActorSubject)
	builder.WriteString(", ")
	builder.WriteString("actor_client_id=")
	builder.WriteString(_m.ActorClientID)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("trace_id=")
	builder.WriteString(_m.TraceID)
	builder.WriteString(", ")
	builder.WriteString("before=")
	builder.WriteString(fmt.Sprintf("%v", _m.Before))
	builder.WriteString(", ")
	builder.WriteString("after=")
	builder.WriteString(fmt.Sprintf("%v", _m.After))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PolicyAudits is a parsable slice of PolicyAudit.
type PolicyAudits []*PolicyAudit
