// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: eagle/system/v1/dict.proto

package systemv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationDictServiceCreateDictData = "/eagle.system.v1.DictService/CreateDictData"
const OperationDictServiceCreateDictType = "/eagle.system.v1.DictService/CreateDictType"
const OperationDictServiceDeleteDictData = "/eagle.system.v1.DictService/DeleteDictData"
const OperationDictServiceDeleteDictType = "/eagle.system.v1.DictService/DeleteDictType"
const OperationDictServiceGetDictDataByType = "/eagle.system.v1.DictService/GetDictDataByType"
const OperationDictServiceListDictData = "/eagle.system.v1.DictService/ListDictData"
const OperationDictServiceListDictTypes = "/eagle.system.v1.DictService/ListDictTypes"
const OperationDictServiceUpdateDictData = "/eagle.system.v1.DictService/UpdateDictData"
const OperationDictServiceUpdateDictType = "/eagle.system.v1.DictService/UpdateDictType"

type DictServiceHTTPServer interface {
	CreateDictData(context.Context, *CreateDictDataRequest) (*CreateDictDataResponse, error)
	CreateDictType(context.Context, *CreateDictTypeRequest) (*CreateDictTypeResponse, error)
	DeleteDictData(context.Context, *DeleteDictDataRequest) (*DeleteDictDataResponse, error)
	DeleteDictType(context.Context, *DeleteDictTypeRequest) (*DeleteDictTypeResponse, error)
	// GetDictDataByType 按类型取字典项，供前端渲染下拉框。任何登录用户都要用，
	// 所以不挂权限码，只校验登录态；结果走 Redis 缓存。
	GetDictDataByType(context.Context, *GetDictDataByTypeRequest) (*GetDictDataByTypeResponse, error)
	ListDictData(context.Context, *ListDictDataRequest) (*ListDictDataResponse, error)
	ListDictTypes(context.Context, *ListDictTypesRequest) (*ListDictTypesResponse, error)
	UpdateDictData(context.Context, *UpdateDictDataRequest) (*UpdateDictDataResponse, error)
	UpdateDictType(context.Context, *UpdateDictTypeRequest) (*UpdateDictTypeResponse, error)
}

func RegisterDictServiceHTTPServer(s *http.Server, srv DictServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/system/dict/types", _DictService_CreateDictType0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/system/dict/types", _DictService_ListDictTypes0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/system/dict/types/{id}", _DictService_UpdateDictType0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/system/dict/types/{id}", _DictService_DeleteDictType0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/system/dict/data", _DictService_CreateDictData0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/system/dict/data", _DictService_ListDictData0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/system/dict/data/{id}", _DictService_UpdateDictData0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/system/dict/data/{id}", _DictService_DeleteDictData0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/system/dict/data/type/{dict_type}", _DictService_GetDictDataByType0_HTTP_Handler(srv))
}

func _DictService_CreateDictType0_HTTP_Handler(srv DictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDictTypeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDictServiceCreateDictType)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDictType(ctx, req.(*CreateDictTypeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateDictTypeResponse)
		return ctx.Result(200, reply)
	}
}

func _DictService_ListDictTypes0_HTTP_Handler(srv DictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDictTypesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDictServiceListDictTypes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDictTypes(ctx, req.(*ListDictTypesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDictTypesResponse)
		return ctx.Result(200, reply)
	}
}

func _DictService_UpdateDictType0_HTTP_Handler(srv DictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDictTypeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDictServiceUpdateDictType)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDictType(ctx, req.(*UpdateDictTypeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateDictTypeResponse)
		return ctx.Result(200, reply)
	}
}

func _DictService_DeleteDictType0_HTTP_Handler(srv DictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDictTypeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDictServiceDeleteDictType)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDictType(ctx, req.(*DeleteDictTypeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteDictTypeResponse)
		return ctx.Result(200, reply)
	}
}

func _DictService_CreateDictData0_HTTP_Handler(srv DictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDictDataRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDictServiceCreateDictData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDictData(ctx, req.(*CreateDictDataRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateDictDataResponse)
		return ctx.Result(200, reply)
	}
}

func _DictService_ListDictData0_HTTP_Handler(srv DictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDictDataRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDictServiceListDictData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDictData(ctx, req.(*ListDictDataRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDictDataResponse)
		return ctx.Result(200, reply)
	}
}

func _DictService_UpdateDictData0_HTTP_Handler(srv DictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDictDataRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDictServiceUpdateDictData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDictData(ctx, req.(*UpdateDictDataRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateDictDataResponse)
		return ctx.Result(200, reply)
	}
}

func _DictService_DeleteDictData0_HTTP_Handler(srv DictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDictDataRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDictServiceDeleteDictData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDictData(ctx, req.(*DeleteDictDataRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteDictDataResponse)
		return ctx.Result(200, reply)
	}
}

func _DictService_GetDictDataByType0_HTTP_Handler(srv DictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDictDataByTypeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDictServiceGetDictDataByType)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDictDataByType(ctx, req.(*GetDictDataByTypeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDictDataByTypeResponse)
		return ctx.Result(200, reply)
	}
}

type DictServiceHTTPClient interface {
	CreateDictData(ctx context.Context, req *CreateDictDataRequest, opts ...http.CallOption) (rsp *CreateDictDataResponse, err error)
	CreateDictType(ctx context.Context, req *CreateDictTypeRequest, opts ...http.CallOption) (rsp *CreateDictTypeResponse, err error)
	DeleteDictData(ctx context.Context, req *DeleteDictDataRequest, opts ...http.CallOption) (rsp *DeleteDictDataResponse, err error)
	DeleteDictType(ctx context.Context, req *DeleteDictTypeRequest, opts ...http.CallOption) (rsp *DeleteDictTypeResponse, err error)
	// GetDictDataByType 按类型取字典项，供前端渲染下拉框。任何登录用户都要用，
	// 所以不挂权限码，只校验登录态；结果走 Redis 缓存。
	GetDictDataByType(ctx context.Context, req *GetDictDataByTypeRequest, opts ...http.CallOption) (rsp *GetDictDataByTypeResponse, err error)
	ListDictData(ctx context.Context, req *ListDictDataRequest, opts ...http.CallOption) (rsp *ListDictDataResponse, err error)
	ListDictTypes(ctx context.Context, req *ListDictTypesRequest, opts ...http.CallOption) (rsp *ListDictTypesResponse, err error)
	UpdateDictData(ctx context.Context, req *UpdateDictDataRequest, opts ...http.CallOption) (rsp *UpdateDictDataResponse, err error)
	UpdateDictType(ctx context.Context, req *UpdateDictTypeRequest, opts ...http.CallOption) (rsp *UpdateDictTypeResponse, err error)
}

type DictServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDictServiceHTTPClient(client *http.Client) DictServiceHTTPClient {
	return &DictServiceHTTPClientImpl{client}
}

func (c *DictServiceHTTPClientImpl) CreateDictData(ctx context.Context, in *CreateDictDataRequest, opts ...http.CallOption) (*CreateDictDataResponse, error) {
	var out CreateDictDataResponse
	pattern := "/v1/system/dict/data"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationDictServiceCreateDictData),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DictServiceHTTPClientImpl) CreateDictType(ctx context.Context, in *CreateDictTypeRequest, opts ...http.CallOption) (*CreateDictTypeResponse, error) {
	var out CreateDictTypeResponse
	pattern := "/v1/system/dict/types"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationDictServiceCreateDictType),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DictServiceHTTPClientImpl) DeleteDictData(ctx context.Context, in *DeleteDictDataRequest, opts ...http.CallOption) (*DeleteDictDataResponse, error) {
	var out DeleteDictDataResponse
	pattern := "/v1/system/dict/data/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationDictServiceDeleteDictData),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DictServiceHTTPClientImpl) DeleteDictType(ctx context.Context, in *DeleteDictTypeRequest, opts ...http.CallOption) (*DeleteDictTypeResponse, error) {
	var out DeleteDictTypeResponse
	pattern := "/v1/system/dict/types/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationDictServiceDeleteDictType),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDictDataByType 按类型取字典项，供前端渲染下拉框。任何登录用户都要用，
// 所以不挂权限码，只校验登录态；结果走 Redis 缓存。
func (c *DictServiceHTTPClientImpl) GetDictDataByType(ctx context.Context, in *GetDictDataByTypeRequest, opts ...http.CallOption) (*GetDictDataByTypeResponse, error) {
	var out GetDictDataByTypeResponse
	pattern := "/v1/system/dict/data/type/{dict_type}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationDictServiceGetDictDataByType),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DictServiceHTTPClientImpl) ListDictData(ctx context.Context, in *ListDictDataRequest, opts ...http.CallOption) (*ListDictDataResponse, error) {
	var out ListDictDataResponse
	pattern := "/v1/system/dict/data"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationDictServiceListDictData),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DictServiceHTTPClientImpl) ListDictTypes(ctx context.Context, in *ListDictTypesRequest, opts ...http.CallOption) (*ListDictTypesResponse, error) {
	var out ListDictTypesResponse
	pattern := "/v1/system/dict/types"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationDictServiceListDictTypes),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DictServiceHTTPClientImpl) UpdateDictData(ctx context.Context, in *UpdateDictDataRequest, opts ...http.CallOption) (*UpdateDictDataResponse, error) {
	var out UpdateDictDataResponse
	pattern := "/v1/system/dict/data/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationDictServiceUpdateDictData),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DictServiceHTTPClientImpl) UpdateDictType(ctx context.Context, in *UpdateDictTypeRequest, opts ...http.CallOption) (*UpdateDictTypeResponse, error) {
	var out UpdateDictTypeResponse
	pattern := "/v1/system/dict/types/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationDictServiceUpdateDictType),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
