// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eagle/system/v1/permission.proto

package systemv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/eagle-go/eagle/api/eagle/annotations/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 权限码，如 system:user:add。目录/菜单可为空，按钮必填
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// 1=目录 2=菜单 3=按钮
	Type      int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Path      string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Component string                 `protobuf:"bytes,7,opt,name=component,proto3" json:"component,omitempty"`
	Icon      string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort      int32                  `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`
	Visible   bool                   `protobuf:"varint,10,opt,name=visible,proto3" json:"visible,omitempty"`
	Status    int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// 整棵权限树的版本，用于管理端乐观并发控制。
	Revision      int64 `protobuf:"varint,14,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Permission) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Permission) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Permission) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Permission) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Permission) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Permission) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Permission) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Permission) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Permission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Permission) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Permission) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      int64                  `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,6,opt,name=component,proto3" json:"component,omitempty"`
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int32                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Visible       bool                   `protobuf:"varint,9,opt,name=visible,proto3" json:"visible,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePermissionRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePermissionRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreatePermissionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreatePermissionRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *CreatePermissionRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreatePermissionRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreatePermissionRequest) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *CreatePermissionRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type GetPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{3}
}

func (x *GetPermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionResponse) Reset() {
	*x = GetPermissionResponse{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionResponse) ProtoMessage() {}

func (x *GetPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionResponse) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{4}
}

func (x *GetPermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *int32                 `protobuf:"varint,1,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Type          *int32                 `protobuf:"varint,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{5}
}

func (x *ListPermissionsRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ListPermissionsRequest) GetType() int32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{6}
}

func (x *ListPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UpdatePermissionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId         int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code             string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Type             int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Path             string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Component        string                 `protobuf:"bytes,7,opt,name=component,proto3" json:"component,omitempty"`
	Icon             string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort             int32                  `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`
	Visible          bool                   `protobuf:"varint,10,opt,name=visible,proto3" json:"visible,omitempty"`
	Status           int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	ExpectedRevision *int64                 `protobuf:"varint,12,opt,name=expected_revision,json=expectedRevision,proto3,oneof" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePermissionRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UpdatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePermissionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePermissionRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdatePermissionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdatePermissionRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *UpdatePermissionRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdatePermissionRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdatePermissionRequest) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *UpdatePermissionRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdatePermissionRequest) GetExpectedRevision() int64 {
	if x != nil && x.ExpectedRevision != nil {
		return *x.ExpectedRevision
	}
	return 0
}

type UpdatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionResponse) Reset() {
	*x = UpdatePermissionResponse{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionResponse) ProtoMessage() {}

func (x *UpdatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type DeletePermissionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedRevision *int64                 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3,oneof" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeletePermissionRequest) GetExpectedRevision() int64 {
	if x != nil && x.ExpectedRevision != nil {
		return *x.ExpectedRevision
	}
	return 0
}

type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{10}
}

type GetMyMenusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyMenusRequest) Reset() {
	*x = GetMyMenusRequest{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyMenusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyMenusRequest) ProtoMessage() {}

func (x *GetMyMenusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyMenusRequest.ProtoReflect.Descriptor instead.
func (*GetMyMenusRequest) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{11}
}

type GetMyMenusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前用户可见的目录与菜单（不含按钮），平铺返回
	Menus []*Permission `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	// 当前用户的全部权限码，前端用于按钮级显隐
	PermissionCodes []string `protobuf:"bytes,2,rep,name=permission_codes,json=permissionCodes,proto3" json:"permission_codes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMyMenusResponse) Reset() {
	*x = GetMyMenusResponse{}
	mi := &file_eagle_system_v1_permission_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyMenusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyMenusResponse) ProtoMessage() {}

func (x *GetMyMenusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eagle_system_v1_permission_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyMenusResponse.ProtoReflect.Descriptor instead.
func (*GetMyMenusResponse) Descriptor() ([]byte, []int) {
	return file_eagle_system_v1_permission_proto_rawDescGZIP(), []int{12}
}

func (x *GetMyMenusResponse) GetMenus() []*Permission {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *GetMyMenusResponse) GetPermissionCodes() []string {
	if x != nil {
		return x.PermissionCodes
	}
	return nil
}

var File_eagle_system_v1_permission_proto protoreflect.FileDescriptor

const file_eagle_system_v1_permission_proto_rawDesc = "" +
	"\n" +
	" eagle/system/v1/permission.proto\x12\x0feagle.system.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1feagle/annotations/v1/perm.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x03\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\a \x01(\tR\tcomponent\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\t \x01(\x05R\x04sort\x12\x18\n" +
	"\avisible\x18\n" +
	" \x01(\bR\avisible\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1a\n" +
	"\brevision\x18\x0e \x01(\x03R\brevision\"\x82\x03\n" +
	"\x17CreatePermissionRequest\x12$\n" +
	"\tparent_id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\bparentId\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x04name\x12O\n" +
	"\x04code\x18\x03 \x01(\tB;\xbaH8\xd8\x01\x01r3\x18\x80\x012.^[a-zA-Z][a-zA-Z0-9]*(:[a-zA-Z][a-zA-Z0-9]*)+$R\x04code\x12\x1d\n" +
	"\x04type\x18\x04 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x03(\x01R\x04type\x12\x1c\n" +
	"\x04path\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x04path\x12&\n" +
	"\tcomponent\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\tcomponent\x12\x1b\n" +
	"\x04icon\x18\a \x01(\tB\a\xbaH\x04r\x02\x18@R\x04icon\x12\x12\n" +
	"\x04sort\x18\b \x01(\x05R\x04sort\x12\x18\n" +
	"\avisible\x18\t \x01(\bR\avisible\x12!\n" +
	"\x06status\x18\n" +
	" \x01(\x05B\t\xbaH\x06\x1a\x040\x000\x01R\x06status\"W\n" +
	"\x18CreatePermissionResponse\x12;\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x1b.eagle.system.v1.PermissionR\n" +
	"permission\"/\n" +
	"\x14GetPermissionRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x02id\"T\n" +
	"\x15GetPermissionResponse\x12;\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x1b.eagle.system.v1.PermissionR\n" +
	"permission\"x\n" +
	"\x16ListPermissionsRequest\x12&\n" +
	"\x06status\x18\x01 \x01(\x05B\t\xbaH\x06\x1a\x040\x000\x01H\x00R\x06status\x88\x01\x01\x12\"\n" +
	"\x04type\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x03(\x01H\x01R\x04type\x88\x01\x01B\t\n" +
	"\a_statusB\a\n" +
	"\x05_type\"X\n" +
	"\x17ListPermissionsResponse\x12=\n" +
	"\vpermissions\x18\x01 \x03(\v2\x1b.eagle.system.v1.PermissionR\vpermissions\"\xec\x03\n" +
	"\x17UpdatePermissionRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x02id\x12$\n" +
	"\tparent_id\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\bparentId\x12\x1d\n" +
	"\x04name\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x04name\x12O\n" +
	"\x04code\x18\x04 \x01(\tB;\xbaH8\xd8\x01\x01r3\x18\x80\x012.^[a-zA-Z][a-zA-Z0-9]*(:[a-zA-Z][a-zA-Z0-9]*)+$R\x04code\x12\x1d\n" +
	"\x04type\x18\x05 \x01(\x05B\t\xbaH\x06\x1a\x04\x18\x03(\x01R\x04type\x12\x1c\n" +
	"\x04path\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x04path\x12&\n" +
	"\tcomponent\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\tcomponent\x12\x1b\n" +
	"\x04icon\x18\b \x01(\tB\a\xbaH\x04r\x02\x18@R\x04icon\x12\x12\n" +
	"\x04sort\x18\t \x01(\x05R\x04sort\x12\x18\n" +
	"\avisible\x18\n" +
	" \x01(\bR\avisible\x12!\n" +
	"\x06status\x18\v \x01(\x05B\t\xbaH\x06\x1a\x040\x000\x01R\x06status\x129\n" +
	"\x11expected_revision\x18\f \x01(\x03B\a\xbaH\x04\"\x02 \x00H\x00R\x10expectedRevision\x88\x01\x01B\x14\n" +
	"\x12_expected_revision\"W\n" +
	"\x18UpdatePermissionResponse\x12;\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x1b.eagle.system.v1.PermissionR\n" +
	"permission\"\x83\x01\n" +
	"\x17DeletePermissionRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x02id\x129\n" +
	"\x11expected_revision\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00H\x00R\x10expectedRevision\x88\x01\x01B\x14\n" +
	"\x12_expected_revision\"\x1a\n" +
	"\x18DeletePermissionResponse\"\x13\n" +
	"\x11GetMyMenusRequest\"r\n" +
	"\x12GetMyMenusResponse\x121\n" +
	"\x05menus\x18\x01 \x03(\v2\x1b.eagle.system.v1.PermissionR\x05menus\x12)\n" +
	"\x10permission_codes\x18\x02 \x03(\tR\x0fpermissionCodes2\xeb\a\n" +
	"\x11PermissionService\x12\xa7\x01\n" +
	"\x10CreatePermission\x12(.eagle.system.v1.CreatePermissionRequest\x1a).eagle.system.v1.CreatePermissionResponse\">\x8a\xb5\x18\x15system:permission:add\x98\xb5\x18\x03\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/system/permissions\x12\xa2\x01\n" +
	"\rGetPermission\x12%.eagle.system.v1.GetPermissionRequest\x1a&.eagle.system.v1.GetPermissionResponse\"B\x8a\xb5\x18\x17system:permission:query\x98\xb5\x18\x03\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/system/permissions/{id}\x12\xa2\x01\n" +
	"\x0fListPermissions\x12'.eagle.system.v1.ListPermissionsRequest\x1a(.eagle.system.v1.ListPermissionsResponse\"<\x8a\xb5\x18\x16system:permission:list\x98\xb5\x18\x03\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/system/permissions\x12\xad\x01\n" +
	"\x10UpdatePermission\x12(.eagle.system.v1.UpdatePermissionRequest\x1a).eagle.system.v1.UpdatePermissionResponse\"D\x8a\xb5\x18\x16system:permission:edit\x98\xb5\x18\x03\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/v1/system/permissions/{id}\x12\xac\x01\n" +
	"\x10DeletePermission\x12(.eagle.system.v1.DeletePermissionRequest\x1a).eagle.system.v1.DeletePermissionResponse\"C\x8a\xb5\x18\x18system:permission:remove\x98\xb5\x18\x03\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/system/permissions/{id}\x12\x82\x01\n" +
	"\n" +
	"GetMyMenus\x12\".eagle.system.v1.GetMyMenusRequest\x1a#.eagle.system.v1.GetMyMenusResponse\"+\x98\xb5\x18\x02\x82\xd3\xe4\x93\x02!\x12\x1f/v1/system/permissions/me/menusB8Z6github.com/eagle-go/eagle/api/eagle/system/v1;systemv1b\x06proto3"

var (
	file_eagle_system_v1_permission_proto_rawDescOnce sync.Once
	file_eagle_system_v1_permission_proto_rawDescData []byte
)

func file_eagle_system_v1_permission_proto_rawDescGZIP() []byte {
	file_eagle_system_v1_permission_proto_rawDescOnce.Do(func() {
		file_eagle_system_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eagle_system_v1_permission_proto_rawDesc), len(file_eagle_system_v1_permission_proto_rawDesc)))
	})
	return file_eagle_system_v1_permission_proto_rawDescData
}

var file_eagle_system_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_eagle_system_v1_permission_proto_goTypes = []any{
	(*Permission)(nil),               // 0: eagle.system.v1.Permission
	(*CreatePermissionRequest)(nil),  // 1: eagle.system.v1.CreatePermissionRequest
	(*CreatePermissionResponse)(nil), // 2: eagle.system.v1.CreatePermissionResponse
	(*GetPermissionRequest)(nil),     // 3: eagle.system.v1.GetPermissionRequest
	(*GetPermissionResponse)(nil),    // 4: eagle.system.v1.GetPermissionResponse
	(*ListPermissionsRequest)(nil),   // 5: eagle.system.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),  // 6: eagle.system.v1.ListPermissionsResponse
	(*UpdatePermissionRequest)(nil),  // 7: eagle.system.v1.UpdatePermissionRequest
	(*UpdatePermissionResponse)(nil), // 8: eagle.system.v1.UpdatePermissionResponse
	(*DeletePermissionRequest)(nil),  // 9: eagle.system.v1.DeletePermissionRequest
	(*DeletePermissionResponse)(nil), // 10: eagle.system.v1.DeletePermissionResponse
	(*GetMyMenusRequest)(nil),        // 11: eagle.system.v1.GetMyMenusRequest
	(*GetMyMenusResponse)(nil),       // 12: eagle.system.v1.GetMyMenusResponse
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_eagle_system_v1_permission_proto_depIdxs = []int32{
	13, // 0: eagle.system.v1.Permission.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: eagle.system.v1.Permission.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: eagle.system.v1.CreatePermissionResponse.permission:type_name -> eagle.system.v1.Permission
	0,  // 3: eagle.system.v1.GetPermissionResponse.permission:type_name -> eagle.system.v1.Permission
	0,  // 4: eagle.system.v1.ListPermissionsResponse.permissions:type_name -> eagle.system.v1.Permission
	0,  // 5: eagle.system.v1.UpdatePermissionResponse.permission:type_name -> eagle.system.v1.Permission
	0,  // 6: eagle.system.v1.GetMyMenusResponse.menus:type_name -> eagle.system.v1.Permission
	1,  // 7: eagle.system.v1.PermissionService.CreatePermission:input_type -> eagle.system.v1.CreatePermissionRequest
	3,  // 8: eagle.system.v1.PermissionService.GetPermission:input_type -> eagle.system.v1.GetPermissionRequest
	5,  // 9: eagle.system.v1.PermissionService.ListPermissions:input_type -> eagle.system.v1.ListPermissionsRequest
	7,  // 10: eagle.system.v1.PermissionService.UpdatePermission:input_type -> eagle.system.v1.UpdatePermissionRequest
	9,  // 11: eagle.system.v1.PermissionService.DeletePermission:input_type -> eagle.system.v1.DeletePermissionRequest
	11, // 12: eagle.system.v1.PermissionService.GetMyMenus:input_type -> eagle.system.v1.GetMyMenusRequest
	2,  // 13: eagle.system.v1.PermissionService.CreatePermission:output_type -> eagle.system.v1.CreatePermissionResponse
	4,  // 14: eagle.system.v1.PermissionService.GetPermission:output_type -> eagle.system.v1.GetPermissionResponse
	6,  // 15: eagle.system.v1.PermissionService.ListPermissions:output_type -> eagle.system.v1.ListPermissionsResponse
	8,  // 16: eagle.system.v1.PermissionService.UpdatePermission:output_type -> eagle.system.v1.UpdatePermissionResponse
	10, // 17: eagle.system.v1.PermissionService.DeletePermission:output_type -> eagle.system.v1.DeletePermissionResponse
	12, // 18: eagle.system.v1.PermissionService.GetMyMenus:output_type -> eagle.system.v1.GetMyMenusResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_eagle_system_v1_permission_proto_init() }
func file_eagle_system_v1_permission_proto_init() {
	if File_eagle_system_v1_permission_proto != nil {
		return
	}
	file_eagle_system_v1_permission_proto_msgTypes[5].OneofWrappers = []any{}
	file_eagle_system_v1_permission_proto_msgTypes[7].OneofWrappers = []any{}
	file_eagle_system_v1_permission_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eagle_system_v1_permission_proto_rawDesc), len(file_eagle_system_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eagle_system_v1_permission_proto_goTypes,
		DependencyIndexes: file_eagle_system_v1_permission_proto_depIdxs,
		MessageInfos:      file_eagle_system_v1_permission_proto_msgTypes,
	}.Build()
	File_eagle_system_v1_permission_proto = out.File
	file_eagle_system_v1_permission_proto_goTypes = nil
	file_eagle_system_v1_permission_proto_depIdxs = nil
}
