// Code generated by ent, DO NOT EDIT.

package policyaudit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/eagle-go/eagle/internal/platform/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLTE(FieldID, id))
}

// PolicyVersion applies equality check predicate on the "policy_version" field. It's identical to PolicyVersionEQ.
func PolicyVersion(v int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldPolicyVersion, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldAction, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldTarget, v))
}

// ActorSubject applies equality check predicate on the "actor_subject" field. It's identical to ActorSubjectEQ.
func ActorSubject(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldActorSubject, v))
}

// ActorClientID applies equality check predicate on the "actor_client_id" field. It's identical to ActorClientIDEQ.
func ActorClientID(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldActorClientID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldRequestID, v))
}

// TraceID applies equality check predicate on the "trace_id" field. It's identical to TraceIDEQ.
func TraceID(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldTraceID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// PolicyVersionEQ applies the EQ predicate on the "policy_version" field.
func PolicyVersionEQ(v int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldPolicyVersion, v))
}

// PolicyVersionNEQ applies the NEQ predicate on the "policy_version" field.
func PolicyVersionNEQ(v int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNEQ(FieldPolicyVersion, v))
}

// PolicyVersionIn applies the In predicate on the "policy_version" field.
func PolicyVersionIn(vs ...int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldIn(FieldPolicyVersion, vs...))
}

// PolicyVersionNotIn applies the NotIn predicate on the "policy_version" field.
func PolicyVersionNotIn(vs ...int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNotIn(FieldPolicyVersion, vs...))
}

// PolicyVersionGT applies the GT predicate on the "policy_version" field.
func PolicyVersionGT(v int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGT(FieldPolicyVersion, v))
}

// PolicyVersionGTE applies the GTE predicate on the "policy_version" field.
func PolicyVersionGTE(v int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGTE(FieldPolicyVersion, v))
}

// PolicyVersionLT applies the LT predicate on the "policy_version" field.
func PolicyVersionLT(v int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLT(FieldPolicyVersion, v))
}

// PolicyVersionLTE applies the LTE predicate on the "policy_version" field.
func PolicyVersionLTE(v int64) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLTE(FieldPolicyVersion, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContainsFold(FieldAction, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContainsFold(FieldTarget, v))
}

// ActorSubjectEQ applies the EQ predicate on the "actor_subject" field.
func ActorSubjectEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldActorSubject, v))
}

// ActorSubjectNEQ applies the NEQ predicate on the "actor_subject" field.
func ActorSubjectNEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNEQ(FieldActorSubject, v))
}

// ActorSubjectIn applies the In predicate on the "actor_subject" field.
func ActorSubjectIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldIn(FieldActorSubject, vs...))
}

// ActorSubjectNotIn applies the NotIn predicate on the "actor_subject" field.
func ActorSubjectNotIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNotIn(FieldActorSubject, vs...))
}

// ActorSubjectGT applies the GT predicate on the "actor_subject" field.
func ActorSubjectGT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGT(FieldActorSubject, v))
}

// ActorSubjectGTE applies the GTE predicate on the "actor_subject" field.
func ActorSubjectGTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGTE(FieldActorSubject, v))
}

// ActorSubjectLT applies the LT predicate on the "actor_subject" field.
func ActorSubjectLT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLT(FieldActorSubject, v))
}

// ActorSubjectLTE applies the LTE predicate on the "actor_subject" field.
func ActorSubjectLTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLTE(FieldActorSubject, v))
}

// ActorSubjectContains applies the Contains predicate on the "actor_subject" field.
func ActorSubjectContains(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContains(FieldActorSubject, v))
}

// ActorSubjectHasPrefix applies the HasPrefix predicate on the "actor_subject" field.
func ActorSubjectHasPrefix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasPrefix(FieldActorSubject, v))
}

// ActorSubjectHasSuffix applies the HasSuffix predicate on the "actor_subject" field.
func ActorSubjectHasSuffix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasSuffix(FieldActorSubject, v))
}

// ActorSubjectEqualFold applies the EqualFold predicate on the "actor_subject" field.
func ActorSubjectEqualFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEqualFold(FieldActorSubject, v))
}

// ActorSubjectContainsFold applies the ContainsFold predicate on the "actor_subject" field.
func ActorSubjectContainsFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContainsFold(FieldActorSubject, v))
}

// ActorClientIDEQ applies the EQ predicate on the "actor_client_id" field.
func ActorClientIDEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldActorClientID, v))
}

// ActorClientIDNEQ applies the NEQ predicate on the "actor_client_id" field.
func ActorClientIDNEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNEQ(FieldActorClientID, v))
}

// ActorClientIDIn applies the In predicate on the "actor_client_id" field.
func ActorClientIDIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldIn(FieldActorClientID, vs...))
}

// ActorClientIDNotIn applies the NotIn predicate on the "actor_client_id" field.
func ActorClientIDNotIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNotIn(FieldActorClientID, vs...))
}

// ActorClientIDGT applies the GT predicate on the "actor_client_id" field.
func ActorClientIDGT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGT(FieldActorClientID, v))
}

// ActorClientIDGTE applies the GTE predicate on the "actor_client_id" field.
func ActorClientIDGTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGTE(FieldActorClientID, v))
}

// ActorClientIDLT applies the LT predicate on the "actor_client_id" field.
func ActorClientIDLT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLT(FieldActorClientID, v))
}

// ActorClientIDLTE applies the LTE predicate on the "actor_client_id" field.
func ActorClientIDLTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLTE(FieldActorClientID, v))
}

// ActorClientIDContains applies the Contains predicate on the "actor_client_id" field.
func ActorClientIDContains(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContains(FieldActorClientID, v))
}

// ActorClientIDHasPrefix applies the HasPrefix predicate on the "actor_client_id" field.
func ActorClientIDHasPrefix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasPrefix(FieldActorClientID, v))
}

// ActorClientIDHasSuffix applies the HasSuffix predicate on the "actor_client_id" field.
func ActorClientIDHasSuffix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasSuffix(FieldActorClientID, v))
}

// ActorClientIDEqualFold applies the EqualFold predicate on the "actor_client_id" field.
func ActorClientIDEqualFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEqualFold(FieldActorClientID, v))
}

// ActorClientIDContainsFold applies the ContainsFold predicate on the "actor_client_id" field.
func ActorClientIDContainsFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContainsFold(FieldActorClientID, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContainsFold(FieldRequestID, v))
}

// TraceIDEQ applies the EQ predicate on the "trace_id" field.
func TraceIDEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldTraceID, v))
}

// TraceIDNEQ applies the NEQ predicate on the "trace_id" field.
func TraceIDNEQ(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNEQ(FieldTraceID, v))
}

// TraceIDIn applies the In predicate on the "trace_id" field.
func TraceIDIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldIn(FieldTraceID, vs...))
}

// TraceIDNotIn applies the NotIn predicate on the "trace_id" field.
func TraceIDNotIn(vs ...string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNotIn(FieldTraceID, vs...))
}

// TraceIDGT applies the GT predicate on the "trace_id" field.
func TraceIDGT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGT(FieldTraceID, v))
}

// TraceIDGTE applies the GTE predicate on the "trace_id" field.
func TraceIDGTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGTE(FieldTraceID, v))
}

// TraceIDLT applies the LT predicate on the "trace_id" field.
func TraceIDLT(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLT(FieldTraceID, v))
}

// TraceIDLTE applies the LTE predicate on the "trace_id" field.
func TraceIDLTE(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLTE(FieldTraceID, v))
}

// TraceIDContains applies the Contains predicate on the "trace_id" field.
func TraceIDContains(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContains(FieldTraceID, v))
}

// TraceIDHasPrefix applies the HasPrefix predicate on the "trace_id" field.
func TraceIDHasPrefix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasPrefix(FieldTraceID, v))
}

// TraceIDHasSuffix applies the HasSuffix predicate on the "trace_id" field.
func TraceIDHasSuffix(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldHasSuffix(FieldTraceID, v))
}

// TraceIDEqualFold applies the EqualFold predicate on the "trace_id" field.
func TraceIDEqualFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEqualFold(FieldTraceID, v))
}

// TraceIDContainsFold applies the ContainsFold predicate on the "trace_id" field.
func TraceIDContainsFold(v string) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldContainsFold(FieldTraceID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PolicyAudit) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PolicyAudit) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PolicyAudit) predicate.PolicyAudit {
	return predicate.PolicyAudit(sql.NotPredicates(p))
}
