apiVersion: v1
kind: Secret
metadata:
  name: eagle-runtime
  namespace: eagle
type: Opaque
stringData:
  admin-database-dsn: CHANGE_ME
  product-database-dsn: CHANGE_ME
  order-database-dsn: CHANGE_ME
  product-service-auth-client-secret: CHANGE_ME
  order-service-auth-client-secret: CHANGE_ME
  rabbitmq-url: CHANGE_ME
  redis-password: CHANGE_ME
  s3-access-key: CHANGE_ME
  s3-secret-key: CHANGE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: eagle-tls
  namespace: eagle
type: kubernetes.io/tls
stringData:
  tls.crt: CHANGE_ME
  tls.key: CHANGE_ME
