// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eagle/file/v1/error_reason.proto

package filev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorReason identifies file-module failures independently of transport status codes.
type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED               ErrorReason = 0
	ErrorReason_ERROR_REASON_FILE_NOT_FOUND            ErrorReason = 50
	ErrorReason_ERROR_REASON_FILE_TOO_LARGE            ErrorReason = 51
	ErrorReason_ERROR_REASON_INVALID_FILE_NAME         ErrorReason = 52
	ErrorReason_ERROR_REASON_INVALID_FILE_CONTENT_TYPE ErrorReason = 53
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ERROR_REASON_UNSPECIFIED",
		50: "ERROR_REASON_FILE_NOT_FOUND",
		51: "ERROR_REASON_FILE_TOO_LARGE",
		52: "ERROR_REASON_INVALID_FILE_NAME",
		53: "ERROR_REASON_INVALID_FILE_CONTENT_TYPE",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED":               0,
		"ERROR_REASON_FILE_NOT_FOUND":            50,
		"ERROR_REASON_FILE_TOO_LARGE":            51,
		"ERROR_REASON_INVALID_FILE_NAME":         52,
		"ERROR_REASON_INVALID_FILE_CONTENT_TYPE": 53,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_eagle_file_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_eagle_file_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_eagle_file_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_eagle_file_v1_error_reason_proto protoreflect.FileDescriptor

const file_eagle_file_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	" eagle/file/v1/error_reason.proto\x12\reagle.file.v1*\xbd\x01\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_REASON_FILE_NOT_FOUND\x102\x12\x1f\n" +
	"\x1bERROR_REASON_FILE_TOO_LARGE\x103\x12\"\n" +
	"\x1eERROR_REASON_INVALID_FILE_NAME\x104\x12*\n" +
	"&ERROR_REASON_INVALID_FILE_CONTENT_TYPE\x105B4Z2github.com/eagle-go/eagle/api/eagle/file/v1;filev1b\x06proto3"

var (
	file_eagle_file_v1_error_reason_proto_rawDescOnce sync.Once
	file_eagle_file_v1_error_reason_proto_rawDescData []byte
)

func file_eagle_file_v1_error_reason_proto_rawDescGZIP() []byte {
	file_eagle_file_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_eagle_file_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eagle_file_v1_error_reason_proto_rawDesc), len(file_eagle_file_v1_error_reason_proto_rawDesc)))
	})
	return file_eagle_file_v1_error_reason_proto_rawDescData
}

var file_eagle_file_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eagle_file_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: eagle.file.v1.ErrorReason
}
var file_eagle_file_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_eagle_file_v1_error_reason_proto_init() }
func file_eagle_file_v1_error_reason_proto_init() {
	if File_eagle_file_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eagle_file_v1_error_reason_proto_rawDesc), len(file_eagle_file_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eagle_file_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_eagle_file_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_eagle_file_v1_error_reason_proto_enumTypes,
	}.Build()
	File_eagle_file_v1_error_reason_proto = out.File
	file_eagle_file_v1_error_reason_proto_goTypes = nil
	file_eagle_file_v1_error_reason_proto_depIdxs = nil
}
