// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: eagle/annotations/v1/perm.proto

package annotationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_eagle_annotations_v1_perm_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "eagle.annotations.v1.perm",
		Tag:           "bytes,50001,opt,name=perm",
		Filename:      "eagle/annotations/v1/perm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "eagle.annotations.v1.public",
		Tag:           "varint,50002,opt,name=public",
		Filename:      "eagle/annotations/v1/perm.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// 调用该方法所需的权限码，例如 "system:user:add"。
	// 留空表示只校验登录态、不校验具体权限。
	//
	// optional string perm = 50001;
	E_Perm = &file_eagle_annotations_v1_perm_proto_extTypes[0]
	// 标记为公开方法，跳过登录态校验（如登录、健康检查、OIDC discovery）。
	// 显式声明而非靠路径前缀匹配，避免新增接口时漏配导致意外裸奔。
	//
	// optional bool public = 50002;
	E_Public = &file_eagle_annotations_v1_perm_proto_extTypes[1]
)

var File_eagle_annotations_v1_perm_proto protoreflect.FileDescriptor

const file_eagle_annotations_v1_perm_proto_rawDesc = "" +
	"\n" +
	"\x1feagle/annotations/v1/perm.proto\x12\x14eagle.annotations.v1\x1a google/protobuf/descriptor.proto:4\n" +
	"\x04perm\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\x04perm:8\n" +
	"\x06public\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\bR\x06publicBBZ@github.com/eagle-go/eagle/api/eagle/annotations/v1;annotationsv1b\x06proto3"

var file_eagle_annotations_v1_perm_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_eagle_annotations_v1_perm_proto_depIdxs = []int32{
	0, // 0: eagle.annotations.v1.perm:extendee -> google.protobuf.MethodOptions
	0, // 1: eagle.annotations.v1.public:extendee -> google.protobuf.MethodOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_eagle_annotations_v1_perm_proto_init() }
func file_eagle_annotations_v1_perm_proto_init() {
	if File_eagle_annotations_v1_perm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eagle_annotations_v1_perm_proto_rawDesc), len(file_eagle_annotations_v1_perm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_eagle_annotations_v1_perm_proto_goTypes,
		DependencyIndexes: file_eagle_annotations_v1_perm_proto_depIdxs,
		ExtensionInfos:    file_eagle_annotations_v1_perm_proto_extTypes,
	}.Build()
	File_eagle_annotations_v1_perm_proto = out.File
	file_eagle_annotations_v1_perm_proto_goTypes = nil
	file_eagle_annotations_v1_perm_proto_depIdxs = nil
}
